/**
 * API-only OpenAPI example payloads keyed by runtime schema export name.
 * Runtime modules (entities, sync, http) must not import these — validation runs here.
 */
import { EXAMPLE_API_KEY_LIST_ITEM } from "#openapi/fixtures/entities.js";
import { EXAMPLE_ERROR_400, EXAMPLE_SYNC_CONFLICT_ERROR } from "#openapi/fixtures/errors.js";
import * as requests from "#openapi/fixtures/requests.js";
import * as responses from "#openapi/fixtures/schema-examples.js";

export const OPENAPI_SCHEMA_EXAMPLES: Record<string, unknown> = {
  addContactsToGroupRequestSchema: requests.EXAMPLE_ADD_TO_GROUP_REQUEST,
  addContactsToGroupResponseSchema: responses.EXAMPLE_ADD_CONTACTS_TO_GROUP_RESPONSE,
  addContactsToTagResponseSchema: responses.EXAMPLE_ADD_CONTACTS_TO_TAG_RESPONSE,
  apiErrorResponseSchema: EXAMPLE_ERROR_400,
  apiKeyCreatedSchema: responses.EXAMPLE_API_KEY_CREATED_RESPONSE,
  apiKeyListItemSchema: EXAMPLE_API_KEY_LIST_ITEM,
  apiKeysListResponseSchema: responses.EXAMPLE_API_KEYS_LIST_RESPONSE,
  apiSuccessResponseSchema: responses.EXAMPLE_API_SUCCESS_RESPONSE,
  bySocialLookupResponseSchema: responses.EXAMPLE_BY_SOCIAL_LOOKUP_RESPONSE,
  chatMessagesListResponseSchema: responses.EXAMPLE_CHAT_MESSAGES_LIST_RESPONSE,
  chatRequestSchema: requests.EXAMPLE_CHAT_REQUEST,
  chatSessionCreatedResponseSchema: responses.EXAMPLE_CHAT_SESSION_CREATED_RESPONSE,
  chatSessionResponseSchema: responses.EXAMPLE_CHAT_SESSION_CREATED_RESPONSE,
  chatSessionsListResponseSchema: responses.EXAMPLE_CHAT_SESSIONS_LIST_RESPONSE,
  contactGroupsResponseSchema: responses.EXAMPLE_CONTACT_GROUPS_RESPONSE,
  contactRelationshipResponseSchema: responses.EXAMPLE_CONTACT_RELATIONSHIP_RESPONSE,
  contactRelationshipsResponseSchema: responses.EXAMPLE_CONTACT_RELATIONSHIPS_RESPONSE,
  contactResponseSchema: responses.EXAMPLE_CONTACT_RESPONSE,
  contactsListResponseSchema: responses.EXAMPLE_CONTACTS_LIST_RESPONSE,
  contactTagBodySchema: requests.EXAMPLE_CONTACT_TAG_REQUEST,
  contactTagListResponseSchema: responses.EXAMPLE_CONTACT_TAG_LIST_RESPONSE,
  createApiKeyInputSchema: requests.EXAMPLE_CREATE_API_KEY_REQUEST,
  createContactApiInputSchema: requests.EXAMPLE_CREATE_CONTACT_REQUEST,
  createContactBodySchema: requests.EXAMPLE_CREATE_CONTACT_REQUEST,
  createContactRelationshipInputSchema: requests.EXAMPLE_CREATE_RELATIONSHIP_REQUEST,
  createContactResponseSchema: responses.EXAMPLE_CREATE_CONTACT_RESPONSE,
  createGroupSchema: requests.EXAMPLE_CREATE_GROUP_REQUEST,
  createInteractionInputSchema: requests.EXAMPLE_CREATE_INTERACTION_REQUEST,
  createTagInputSchema: requests.EXAMPLE_CREATE_TAG_REQUEST,
  declineMergeRecommendationResponseSchema: responses.EXAMPLE_DECLINE_MERGE_RECOMMENDATION_RESPONSE,
  deleteContactResponseSchema: responses.EXAMPLE_DELETE_CONTACT_RESPONSE,
  deleteContactsRequestSchema: requests.EXAMPLE_DELETE_CONTACTS_REQUEST,
  deleteContactsResponseSchema: responses.EXAMPLE_DELETE_CONTACTS_RESPONSE,
  enrichContactRequestSchema: requests.EXAMPLE_ENRICH_CONTACT_REQUEST,
  enrichEligibleCountResponseSchema: responses.EXAMPLE_ENRICH_ELIGIBLE_COUNT_RESPONSE,
  enrichQueueInitBodySchema: requests.EXAMPLE_ENRICH_QUEUE_INIT_REQUEST,
  enrichQueueInitResponseSchema: responses.EXAMPLE_ENRICH_QUEUE_INIT_RESPONSE,
  enrichQueueNextBatchResponseSchema: responses.EXAMPLE_ENRICH_QUEUE_NEXT_BATCH_RESPONSE,
  enrichQueuePatchBodySchema: requests.EXAMPLE_ENRICH_QUEUE_PATCH_REQUEST,
  enrichQueueStatusCountsSchema: responses.EXAMPLE_ENRICH_QUEUE_STATUS_COUNTS_RESPONSE,
  feedbackFormSchema: requests.EXAMPLE_FEEDBACK_REQUEST,
  geocodeSuggestResponseSchema: responses.EXAMPLE_GEOCODE_SUGGEST_RESPONSE,
  geocodeTimezoneResponseSchema: responses.EXAMPLE_GEOCODE_TIMEZONE_RESPONSE,
  groupContactsListResponseSchema: responses.EXAMPLE_GROUP_CONTACTS_LIST_RESPONSE,
  groupResponseSchema: responses.EXAMPLE_GROUP_RESPONSE,
  groupsListResponseSchema: responses.EXAMPLE_GROUPS_LIST_RESPONSE,
  importantDatesListResponseSchema: responses.EXAMPLE_IMPORTANT_DATES_LIST_RESPONSE,
  instagramImportCommitRequestSchema: requests.EXAMPLE_INSTAGRAM_IMPORT_COMMIT_REQUEST,
  instagramImportCommitResponseSchema: responses.EXAMPLE_INSTAGRAM_IMPORT_COMMIT_RESPONSE,
  instagramParseResponseSchema: responses.EXAMPLE_INSTAGRAM_PARSE_RESPONSE,
  interactionResponseSchema: responses.EXAMPLE_INTERACTION_RESPONSE,
  interactionsListResponseSchema: responses.EXAMPLE_INTERACTIONS_LIST_RESPONSE,
  linkedInDataRequestSchema: requests.EXAMPLE_LINKEDIN_DATA_REQUEST,
  linkedInDataResponseSchema: responses.EXAMPLE_LINKEDIN_DATA_RESPONSE,
  linkedInDataUpsertResponseSchema: responses.EXAMPLE_LINKEDIN_DATA_UPSERT_RESPONSE,
  linkedInImportCommitRequestSchema: requests.EXAMPLE_LINKEDIN_IMPORT_COMMIT_REQUEST,
  linkedInImportCommitResponseSchema: responses.EXAMPLE_LINKEDIN_IMPORT_COMMIT_RESPONSE,
  linkedInParseResponseSchema: responses.EXAMPLE_LINKEDIN_PARSE_RESPONSE,
  mapAddressPinsResponseSchema: responses.EXAMPLE_MAP_ADDRESS_PINS_RESPONSE,
  mapPinsResponseSchema: responses.EXAMPLE_MAP_PINS_RESPONSE,
  mergeContactsRequestSchema: requests.EXAMPLE_MERGE_CONTACTS_REQUEST,
  mergeContactsResponseSchema: responses.EXAMPLE_MERGE_CONTACTS_RESPONSE,
  mergeRecommendationsResponseSchema: responses.EXAMPLE_MERGE_RECOMMENDATIONS_RESPONSE,
  messageResponseSchema: responses.EXAMPLE_MESSAGE_RESPONSE,
  photoUploadResponseSchema: responses.EXAMPLE_PHOTO_UPLOAD_RESPONSE,
  redirectRequestSchema: requests.EXAMPLE_EXTENSION_REDIRECT_REQUEST,
  redirectResponseSchema: responses.EXAMPLE_REDIRECT_RESPONSE,
  refreshMergeRecommendationsResponseSchema:
    responses.EXAMPLE_REFRESH_MERGE_RECOMMENDATIONS_RESPONSE,
  reminderDigestRequestSchema: requests.EXAMPLE_REMINDER_DIGEST_REQUEST,
  reminderDigestResponseSchema: responses.EXAMPLE_REMINDER_DIGEST_RESPONSE,
  removeContactsFromTagResponseSchema: responses.EXAMPLE_REMOVE_CONTACTS_FROM_TAG_RESPONSE,
  removeGroupMembersRequestSchema: requests.EXAMPLE_REMOVE_FROM_GROUP_REQUEST,
  removeGroupMembersResponseSchema: responses.EXAMPLE_REMOVE_GROUP_MEMBERS_RESPONSE,
  shareContactRequestSchema: requests.EXAMPLE_SHARE_CONTACT_REQUEST,
  syncBootstrapResponseSchema: responses.EXAMPLE_SYNC_BOOTSTRAP_RESPONSE,
  syncConflictErrorResponseSchema: EXAMPLE_SYNC_CONFLICT_ERROR,
  syncPullResponseSchema: responses.EXAMPLE_SYNC_PULL_RESPONSE,
  syncPushRequestSchema: requests.EXAMPLE_SYNC_PUSH_REQUEST,
  syncPushResponseSchema: responses.EXAMPLE_SYNC_PUSH_RESPONSE,
  tagMembershipRequestSchema: requests.EXAMPLE_TAG_MEMBERSHIP_REQUEST,
  tagMembersListResponseSchema: responses.EXAMPLE_TAG_MEMBERS_LIST_RESPONSE,
  tagResponseSchema: responses.EXAMPLE_TAG_RESPONSE,
  tagsListResponseSchema: responses.EXAMPLE_TAGS_LIST_RESPONSE,
  tagUpdateResponseSchema: responses.EXAMPLE_TAG_UPDATE_RESPONSE,
  upcomingRemindersResponseSchema: responses.EXAMPLE_UPCOMING_REMINDERS_RESPONSE,
  updateAccountInputSchema: requests.EXAMPLE_UPDATE_ACCOUNT_REQUEST,
  updateApiKeyLabelInputSchema: requests.EXAMPLE_PATCH_API_KEY_REQUEST,
  updateChatSessionBodySchema: requests.EXAMPLE_UPDATE_CHAT_SESSION_REQUEST,
  updateContactInputSchema: requests.EXAMPLE_PATCH_CONTACT_REQUEST,
  updateContactRelationshipInputSchema: requests.EXAMPLE_PATCH_RELATIONSHIP_REQUEST,
  updateGroupSchema: requests.EXAMPLE_PATCH_GROUP_REQUEST,
  updateInteractionInputSchema: requests.EXAMPLE_PATCH_INTERACTION_REQUEST,
  updateSettingsBodySchema: requests.EXAMPLE_UPDATE_SETTINGS_REQUEST,
  updateTagSchema: requests.EXAMPLE_PATCH_TAG_REQUEST,
  userAccountResponseSchema: responses.EXAMPLE_USER_ACCOUNT_RESPONSE,
  userSettingsResponseSchema: responses.EXAMPLE_USER_SETTINGS_RESPONSE,
  vcardImportCommitRequestSchema: requests.EXAMPLE_VCARD_IMPORT_COMMIT_REQUEST,
  vcardImportCommitResponseSchema: responses.EXAMPLE_VCARD_IMPORT_COMMIT_RESPONSE,
  vcardParseResponseSchema: responses.EXAMPLE_VCARD_PARSE_RESPONSE,
};
