export { Header } from "./Header";
export { About } from "./About";
export { Hero } from "./Hero";
export { Features } from "./Features";
export { Pricing } from "./Pricing";
export { CallToAction } from "./CallToAction";
export { Footer } from "./Footer";
export { Team } from "./Team";
export { Contact } from "./Contact";
