export { CallToAction } from "./CallToAction";
export { Contact } from "./Contact";
export { Faq } from "./Faq";
export { Features } from "./Features";
export { Footer } from "./Footer";
export { Header } from "./Header";
export { Hero } from "./Hero";
export { Pricing } from "./Pricing";
export { Team } from "./Team";
