/** Canonical assistant tool names shared by MCP and in-app chat (sorted). */
export const ASSISTANT_TOOL_NAMES = [
  "create_contact",
  "create_contact_share",
  "create_group",
  "create_group_membership",
  "create_interaction",
  "create_relationship",
  "create_tag",
  "create_tag_membership",
  "delete_contact",
  "delete_group",
  "delete_group_membership",
  "delete_interaction",
  "delete_relationship",
  "delete_tag",
  "delete_tag_membership",
  "get_contact",
  "get_contact_by_social",
  "get_contact_groups",
  "get_contact_linkedin",
  "get_contact_share",
  "get_contact_tags",
  "get_group",
  "get_group_contacts",
  "get_groups",
  "get_important_dates",
  "get_interaction",
  "get_interactions",
  "get_keep_in_touch_contacts",
  "get_keep_in_touch_count",
  "get_relationships",
  "get_tag",
  "get_tag_contacts",
  "get_tags",
  "get_upcoming_reminders",
  "search_contacts",
  "search_groups",
  "search_tags",
  "update_contact",
  "update_group",
  "update_important_dates",
  "update_interaction",
  "update_keep_in_touch",
  "update_relationship",
  "update_tag",
] as const;

export type AssistantToolName = (typeof ASSISTANT_TOOL_NAMES)[number];
