export {
  addContactsToGroupRequestSchema,
  addContactsToGroupResponseSchema,
  contactGroupsResponseSchema,
  createGroupSchema,
  deleteGroupsRequestSchema,
  groupContactsListResponseSchema,
  groupMembersListResponseSchema,
  groupResponseSchema,
  groupSchema,
  groupsListResponseSchema,
  groupWithCountSchema,
  peopleGroupSchema,
  removeGroupMembersRequestSchema,
  removeGroupMembersResponseSchema,
  updateGroupSchema,
} from "./schema.js";
export type {
  AddContactsToGroupRequest,
  AddContactsToGroupResponse,
  ContactGroupsResponse,
  CreateGroupInput,
  DeleteGroupsRequest,
  Group,
  GroupContactsListResponse,
  GroupMembersListResponse,
  GroupResponse,
  GroupsListResponse,
  GroupWithCount,
  PeopleGroup,
  RemoveGroupMembersRequest,
  RemoveGroupMembersResponse,
  UpdateGroupInput,
} from "./types.js";
