/** Generated by apps/api/scripts/generate-api-error-catalog.ts — do not edit manually. */
import type { ApiErrorType } from "./api-error-types.js";

export interface ApiErrorDefinition {
  code: string;
  type: ApiErrorType;
  httpStatus: number;
  docPath: string;
  messageTemplate: string;
}

export const API_ERROR_CODE_ENTRIES = {
  "account_failed_to_delete_account": { code: "account_failed_to_delete_account", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/account_failed_to_delete_account", messageTemplate: "Account Failed To Delete Account" },
  "account_failed_to_generate_avatar_url": { code: "account_failed_to_generate_avatar_url", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/account_failed_to_generate_avatar_url", messageTemplate: "Account Failed To Generate Avatar Url" },
  "account_failed_to_update_account": { code: "account_failed_to_update_account", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/account_failed_to_update_account", messageTemplate: "Account Failed To Update Account" },
  "account_failed_to_upload_profile_photo": { code: "account_failed_to_upload_profile_photo", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/account_failed_to_upload_profile_photo", messageTemplate: "Account Failed To Upload Profile Photo" },
  "account_invalid": { code: "account_invalid", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/account_invalid", messageTemplate: "Account Invalid" },
  "account_photo_invalid_format": { code: "account_photo_invalid_format", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/account_photo_invalid_format", messageTemplate: "Account Photo Invalid Format" },
  "admin_required": { code: "admin_required", type: "authorization_error", httpStatus: 403, docPath: "/docs/api/errors/admin_required", messageTemplate: "Admin Required" },
  "api_key_failed": { code: "api_key_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/api_key_failed", messageTemplate: "Api Key Failed" },
  "api_key_limit_exceeded": { code: "api_key_limit_exceeded", type: "conflict_error", httpStatus: 409, docPath: "/docs/api/errors/api_key_limit_exceeded", messageTemplate: "Api Key Limit Exceeded" },
  "api_key_method_forbidden": { code: "api_key_method_forbidden", type: "authorization_error", httpStatus: 403, docPath: "/docs/api/errors/api_key_method_forbidden", messageTemplate: "Api Key Method Forbidden" },
  "api_key_not_found": { code: "api_key_not_found", type: "not_found_error", httpStatus: 404, docPath: "/docs/api/errors/api_key_not_found", messageTemplate: "Api Key Not Found" },
  "api_key_route_forbidden": { code: "api_key_route_forbidden", type: "authorization_error", httpStatus: 403, docPath: "/docs/api/errors/api_key_route_forbidden", messageTemplate: "Api Key Route Forbidden" },
  "auth_required": { code: "auth_required", type: "authentication_error", httpStatus: 401, docPath: "/docs/api/errors/auth_required", messageTemplate: "Auth Required" },
  "bad_request": { code: "bad_request", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/bad_request", messageTemplate: "Bad Request" },
  "billing_pending_subscription_store_failed": { code: "billing_pending_subscription_store_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/billing_pending_subscription_store_failed", messageTemplate: "Billing Pending Subscription Store Failed" },
  "billing_subscription_upsert_failed": { code: "billing_subscription_upsert_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/billing_subscription_upsert_failed", messageTemplate: "Billing Subscription Upsert Failed" },
  "conflict": { code: "conflict", type: "conflict_error", httpStatus: 409, docPath: "/docs/api/errors/conflict", messageTemplate: "Conflict" },
  "contact_contact_was_created_but_could_not_be_loa": { code: "contact_contact_was_created_but_could_not_be_loa", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_contact_was_created_but_could_not_be_loa", messageTemplate: "Contact Contact Was Created But Could Not Be Loa" },
  "contact_contact_was_created_but_could_not_be_rel": { code: "contact_contact_was_created_but_could_not_be_rel", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_contact_was_created_but_could_not_be_rel", messageTemplate: "Contact Contact Was Created But Could Not Be Rel" },
  "contact_contact_was_updated_but_could_not_be_loa": { code: "contact_contact_was_updated_but_could_not_be_loa", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_contact_was_updated_but_could_not_be_loa", messageTemplate: "Contact Contact Was Updated But Could Not Be Loa" },
  "contact_delete_invalid_body": { code: "contact_delete_invalid_body", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/contact_delete_invalid_body", messageTemplate: "Contact Delete Invalid Body" },
  "contact_delete_self_forbidden": { code: "contact_delete_self_forbidden", type: "authorization_error", httpStatus: 403, docPath: "/docs/api/errors/contact_delete_self_forbidden", messageTemplate: "Contact Delete Self Forbidden" },
  "contact_enrich_failed": { code: "contact_enrich_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_enrich_failed", messageTemplate: "Contact Enrich Failed" },
  "contact_failed": { code: "contact_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_failed", messageTemplate: "Contact Failed" },
  "contact_failed_to_assign_default_group": { code: "contact_failed_to_assign_default_group", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_failed_to_assign_default_group", messageTemplate: "Contact Failed To Assign Default Group" },
  "contact_failed_to_look_up_contact": { code: "contact_failed_to_look_up_contact", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_failed_to_look_up_contact", messageTemplate: "Contact Failed To Look Up Contact" },
  "contact_failed_to_save_socials": { code: "contact_failed_to_save_socials", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_failed_to_save_socials", messageTemplate: "Contact Failed To Save Socials" },
  "contact_failed_to_upload_photo": { code: "contact_failed_to_upload_photo", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_failed_to_upload_photo", messageTemplate: "Contact Failed To Upload Photo" },
  "contact_ids_empty": { code: "contact_ids_empty", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/contact_ids_empty", messageTemplate: "Contact Ids Empty" },
  "contact_ids_invalid_body": { code: "contact_ids_invalid_body", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/contact_ids_invalid_body", messageTemplate: "Contact Ids Invalid Body" },
  "contact_ids_only_myself": { code: "contact_ids_only_myself", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/contact_ids_only_myself", messageTemplate: "Contact Ids Only Myself" },
  "contact_ids_search_failed": { code: "contact_ids_search_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_ids_search_failed", messageTemplate: "Contact Ids Search Failed" },
  "contact_invalid": { code: "contact_invalid", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/contact_invalid", messageTemplate: "Contact Invalid" },
  "contact_location_incomplete": { code: "contact_location_incomplete", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/contact_location_incomplete", messageTemplate: "Contact Location Incomplete" },
  "contact_location_invalid": { code: "contact_location_invalid", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/contact_location_invalid", messageTemplate: "Contact Location Invalid" },
  "contact_merge_failed": { code: "contact_merge_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_merge_failed", messageTemplate: "Contact Merge Failed" },
  "contact_merge_invalid": { code: "contact_merge_invalid", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/contact_merge_invalid", messageTemplate: "Contact Merge Invalid" },
  "contact_merge_same_contact": { code: "contact_merge_same_contact", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/contact_merge_same_contact", messageTemplate: "Contact Merge Same Contact" },
  "contact_merge_socials_failed": { code: "contact_merge_socials_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_merge_socials_failed", messageTemplate: "Contact Merge Socials Failed" },
  "contact_not_found": { code: "contact_not_found", type: "not_found_error", httpStatus: 404, docPath: "/docs/api/errors/contact_not_found", messageTemplate: "Contact Not Found" },
  "contact_share_email_render_failed": { code: "contact_share_email_render_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_share_email_render_failed", messageTemplate: "Contact Share Email Render Failed" },
  "contact_share_email_send_failed": { code: "contact_share_email_send_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_share_email_send_failed", messageTemplate: "Contact Share Email Send Failed" },
  "contact_share_failed": { code: "contact_share_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_share_failed", messageTemplate: "Contact Share Failed" },
  "contact_update_failed": { code: "contact_update_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/contact_update_failed", messageTemplate: "Contact Update Failed" },
  "email_service_not_configured": { code: "email_service_not_configured", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/email_service_not_configured", messageTemplate: "Email Service Not Configured" },
  "export_failed_to_generate": { code: "export_failed_to_generate", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/export_failed_to_generate", messageTemplate: "Export Failed To Generate" },
  "extension_outdated": { code: "extension_outdated", type: "invalid_request_error", httpStatus: 426, docPath: "/docs/api/errors/extension_outdated", messageTemplate: "Extension Outdated" },
  "extension_username_required": { code: "extension_username_required", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/extension_username_required", messageTemplate: "Extension Username Required" },
  "failed_to_create_checkout_session": { code: "failed_to_create_checkout_session", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/failed_to_create_checkout_session", messageTemplate: "Failed To Create Checkout Session" },
  "failed_to_generate_vcard": { code: "failed_to_generate_vcard", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/failed_to_generate_vcard", messageTemplate: "Failed To Generate Vcard" },
  "failed_to_load_profile_contact": { code: "failed_to_load_profile_contact", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/failed_to_load_profile_contact", messageTemplate: "Failed To Load Profile Contact" },
  "failed_to_process_webhook": { code: "failed_to_process_webhook", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/failed_to_process_webhook", messageTemplate: "Failed To Process Webhook" },
  "failed_to_render_or_send_feedback_email_": { code: "failed_to_render_or_send_feedback_email_", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/failed_to_render_or_send_feedback_email_", messageTemplate: "Failed To Render Or Send Feedback Email " },
  "group_add_contacts_invalid_body": { code: "group_add_contacts_invalid_body", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/group_add_contacts_invalid_body", messageTemplate: "Group Add Contacts Invalid Body" },
  "group_failed": { code: "group_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/group_failed", messageTemplate: "Group Failed" },
  "group_member_ids_empty": { code: "group_member_ids_empty", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/group_member_ids_empty", messageTemplate: "Group Member Ids Empty" },
  "group_member_ids_invalid_body": { code: "group_member_ids_invalid_body", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/group_member_ids_invalid_body", messageTemplate: "Group Member Ids Invalid Body" },
  "group_member_ids_search_failed": { code: "group_member_ids_search_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/group_member_ids_search_failed", messageTemplate: "Group Member Ids Search Failed" },
  "group_not_found": { code: "group_not_found", type: "not_found_error", httpStatus: 404, docPath: "/docs/api/errors/group_not_found", messageTemplate: "Group Not Found" },
  "group_remove_members_invalid_body": { code: "group_remove_members_invalid_body", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/group_remove_members_invalid_body", messageTemplate: "Group Remove Members Invalid Body" },
  "chat_quota_exceeded": { code: "chat_quota_exceeded", type: "authorization_error", httpStatus: 403, docPath: "/docs/api/errors/chat_quota_exceeded", messageTemplate: "Chat Quota Exceeded" },
  "chat_session_failed_to_create_session": { code: "chat_session_failed_to_create_session", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/chat_session_failed_to_create_session", messageTemplate: "Chat Session Failed To Create Session" },
  "chat_session_failed_to_update_session": { code: "chat_session_failed_to_update_session", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/chat_session_failed_to_update_session", messageTemplate: "Chat Session Failed To Update Session" },
  "checkout_not_configured": { code: "checkout_not_configured", type: "authorization_error", httpStatus: 403, docPath: "/docs/api/errors/checkout_not_configured", messageTemplate: "Checkout Not Configured" },
  "import_bondery_failed": { code: "import_bondery_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/import_bondery_failed", messageTemplate: "Import Bondery Failed" },
  "import_bondery_invalid": { code: "import_bondery_invalid", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/import_bondery_invalid", messageTemplate: "Import Bondery Invalid" },
  "import_failed": { code: "import_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/import_failed", messageTemplate: "Import Failed" },
  "import_instagram_failed": { code: "import_instagram_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/import_instagram_failed", messageTemplate: "Import Instagram Failed" },
  "import_linkedin_failed": { code: "import_linkedin_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/import_linkedin_failed", messageTemplate: "Import Linkedin Failed" },
  "import_vcard_failed": { code: "import_vcard_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/import_vcard_failed", messageTemplate: "Import Vcard Failed" },
  "important_date_duplicate": { code: "important_date_duplicate", type: "conflict_error", httpStatus: 409, docPath: "/docs/api/errors/important_date_duplicate", messageTemplate: "Important Date Duplicate" },
  "interaction_interaction_was_created_but_could_not_be": { code: "interaction_interaction_was_created_but_could_not_be", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/interaction_interaction_was_created_but_could_not_be", messageTemplate: "Interaction Interaction Was Created But Could Not Be" },
  "interaction_no_fields": { code: "interaction_no_fields", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/interaction_no_fields", messageTemplate: "Interaction No Fields" },
  "interaction_not_found": { code: "interaction_not_found", type: "not_found_error", httpStatus: 404, docPath: "/docs/api/errors/interaction_not_found", messageTemplate: "Interaction Not Found" },
  "interaction_update_failed": { code: "interaction_update_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/interaction_update_failed", messageTemplate: "Interaction Update Failed" },
  "internal_server_error": { code: "internal_server_error", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/internal_server_error", messageTemplate: "Internal Server Error" },
  "invalid_api_key": { code: "invalid_api_key", type: "authentication_error", httpStatus: 401, docPath: "/docs/api/errors/invalid_api_key", messageTemplate: "Invalid Api Key" },
  "merge_recommendation_id_required": { code: "merge_recommendation_id_required", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/merge_recommendation_id_required", messageTemplate: "Merge Recommendation Id Required" },
  "merge_recommendation_not_found": { code: "merge_recommendation_not_found", type: "not_found_error", httpStatus: 404, docPath: "/docs/api/errors/merge_recommendation_not_found", messageTemplate: "Merge Recommendation Not Found" },
  "not_found": { code: "not_found", type: "not_found_error", httpStatus: 404, docPath: "/docs/api/errors/not_found", messageTemplate: "Not Found" },
  "oauth_provider_not_configured": { code: "oauth_provider_not_configured", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/oauth_provider_not_configured", messageTemplate: "Oauth Provider Not Configured" },
  "onboarding_failed_to_dismiss_getting_started": { code: "onboarding_failed_to_dismiss_getting_started", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/onboarding_failed_to_dismiss_getting_started", messageTemplate: "Onboarding Failed To Dismiss Getting Started" },
  "onboarding_failed_to_update_import_follow_up": { code: "onboarding_failed_to_update_import_follow_up", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/onboarding_failed_to_update_import_follow_up", messageTemplate: "Onboarding Failed To Update Import Follow Up" },
  "rate_limit_exceeded": { code: "rate_limit_exceeded", type: "rate_limit_error", httpStatus: 429, docPath: "/docs/api/errors/rate_limit_exceeded", messageTemplate: "Rate Limit Exceeded" },
  "relationship_already_exists": { code: "relationship_already_exists", type: "conflict_error", httpStatus: 409, docPath: "/docs/api/errors/relationship_already_exists", messageTemplate: "Relationship Already Exists" },
  "relationship_failed": { code: "relationship_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/relationship_failed", messageTemplate: "Relationship Failed" },
  "relationship_invalid": { code: "relationship_invalid", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/relationship_invalid", messageTemplate: "Relationship Invalid" },
  "relationship_not_found": { code: "relationship_not_found", type: "not_found_error", httpStatus: 404, docPath: "/docs/api/errors/relationship_not_found", messageTemplate: "Relationship Not Found" },
  "relationship_self_forbidden": { code: "relationship_self_forbidden", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/relationship_self_forbidden", messageTemplate: "Relationship Self Forbidden" },
  "service_auth_invalid": { code: "service_auth_invalid", type: "authentication_error", httpStatus: 401, docPath: "/docs/api/errors/service_auth_invalid", messageTemplate: "Service Auth Invalid" },
  "service_auth_required": { code: "service_auth_required", type: "authentication_error", httpStatus: 401, docPath: "/docs/api/errors/service_auth_required", messageTemplate: "Service Auth Required" },
  "service_unavailable": { code: "service_unavailable", type: "service_unavailable_error", httpStatus: 503, docPath: "/docs/api/errors/service_unavailable", messageTemplate: "Service Unavailable" },
  "session_fetch_failed": { code: "session_fetch_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/session_fetch_failed", messageTemplate: "Session Fetch Failed" },
  "session_settings_missing": { code: "session_settings_missing", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/session_settings_missing", messageTemplate: "Session Settings Missing" },
  "settings_failed_to_create_default_settings": { code: "settings_failed_to_create_default_settings", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/settings_failed_to_create_default_settings", messageTemplate: "Settings Failed To Create Default Settings" },
  "settings_fetch_failed": { code: "settings_fetch_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/settings_fetch_failed", messageTemplate: "Settings Fetch Failed" },
  "settings_no_fields": { code: "settings_no_fields", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/settings_no_fields", messageTemplate: "Settings No Fields" },
  "sqlite_schema_mismatch": { code: "sqlite_schema_mismatch", type: "invalid_request_error", httpStatus: 426, docPath: "/docs/api/errors/sqlite_schema_mismatch", messageTemplate: "Sqlite Schema Mismatch" },
  "sync_conflict": { code: "sync_conflict", type: "conflict_error", httpStatus: 409, docPath: "/docs/api/errors/sync_conflict", messageTemplate: "Sync Conflict" },
  "sync_protocol_mismatch": { code: "sync_protocol_mismatch", type: "invalid_request_error", httpStatus: 426, docPath: "/docs/api/errors/sync_protocol_mismatch", messageTemplate: "Sync Protocol Mismatch" },
  "tag_failed": { code: "tag_failed", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/tag_failed", messageTemplate: "Tag Failed" },
  "tag_not_found": { code: "tag_not_found", type: "not_found_error", httpStatus: 404, docPath: "/docs/api/errors/tag_not_found", messageTemplate: "Tag Not Found" },
  "validation_error": { code: "validation_error", type: "invalid_request_error", httpStatus: 400, docPath: "/docs/api/errors/validation_error", messageTemplate: "Validation Error" },
  "webhook_not_configured": { code: "webhook_not_configured", type: "api_error", httpStatus: 500, docPath: "/docs/api/errors/webhook_not_configured", messageTemplate: "Webhook Not Configured" },
} as const satisfies Record<string, ApiErrorDefinition>;

export type ApiErrorCode = keyof typeof API_ERROR_CODE_ENTRIES;

export const API_ERROR_CODES = Object.keys(API_ERROR_CODE_ENTRIES) as ApiErrorCode[];

export function getErrorDefinition(code: ApiErrorCode): ApiErrorDefinition {
  return API_ERROR_CODE_ENTRIES[code];
}

export function getErrorDocPath(code: ApiErrorCode): string {
  return API_ERROR_CODE_ENTRIES[code].docPath;
}

export function isApiErrorCode(value: string): value is ApiErrorCode {
  return Object.hasOwn(API_ERROR_CODE_ENTRIES, value);
}
