/**
 * Canonical environment variable contract for the Bondery monorepo.
 *
 * Humans edit root `.env.local` using these canonical names.
 * `npm run env` copies identity (or documented aliases) into per-app files.
 *
 * Naming:
 * - BONDERY_PUBLIC_*  — safe for clients
 * - BONDERY_PRIVATE_* — secrets (API / auth setup)
 * - BONDERY_INFRA_*   — deploy / runtime plumbing
 * - BONDERY_OPS_*     — CI only (never synced into app local files)
 */

export type EnvEnvironment = "development" | "production";

export type TargetId = "api" | "webapp" | "website" | "mobile" | "chrome-extension" | "supabase-db";

export type EnvTargetWrite = {
  /** App / package id */
  id: TargetId;
  /**
   * Name written into the target file.
   * Defaults to the canonical name when omitted (identity).
   */
  runtimeName?: string;
  /**
   * When set, derive the value from another canonical key (e.g. callback URL).
   * If `transform` is omitted, copies the source value as-is under `runtimeName`.
   */
  deriveFrom?: string;
  /** Optional value transform when deriving */
  transform?: "webapp-auth-callback" | "supabase-auth-callback";
};

export type EnvVarDef = {
  canonical: string;
  description: string;
  /** Include in generated root `.env.local.example` */
  exampleValue: string;
  /** Group header in generated files */
  group: string;
  requiredIn: EnvEnvironment[];
  secret: boolean;
  targets: EnvTargetWrite[];
  /** When false, omit from turbo cache env arrays (rare) */
  turboAffectsCache?: boolean;
};

export type SyncTargetConfig = {
  id: TargetId;
  /** Relative to repo root */
  devFile: string;
  /** Relative to repo root — committed example regenerated by `npm run env -- --write-examples` */
  exampleFile: string;
  /** Optional alternate example for production shape */
  productionExampleFile?: string;
};

/** Where `npm run env` writes per-app local files */
export const SYNC_TARGETS: SyncTargetConfig[] = [
  {
    devFile: "apps/api/.env.development.local",
    exampleFile: "apps/api/.env.development.example",
    id: "api",
    productionExampleFile: "apps/api/.env.production.example",
  },
  {
    devFile: "apps/webapp/.env.development.local",
    exampleFile: "apps/webapp/.env.development.example",
    id: "webapp",
    productionExampleFile: "apps/webapp/.env.production.example",
  },
  {
    devFile: "apps/website/.env.development.local",
    exampleFile: "apps/website/.env.development.local.example",
    id: "website",
    productionExampleFile: "apps/website/.env.production.local.example",
  },
  {
    devFile: "apps/mobile/.env.local",
    exampleFile: "apps/mobile/.env.example",
    id: "mobile",
  },
  {
    devFile: "apps/chrome-extension/.env.development.local",
    exampleFile: "apps/chrome-extension/.env.development.example",
    id: "chrome-extension",
    productionExampleFile: "apps/chrome-extension/.env.production.example",
  },
  {
    devFile: "apps/supabase-db/.env.local",
    exampleFile: "apps/supabase-db/.env.local.example",
    id: "supabase-db",
  },
];

function t(id: TargetId, runtimeName?: string): EnvTargetWrite {
  return runtimeName ? { id, runtimeName } : { id };
}

export const ENV_MANIFEST: EnvVarDef[] = [
  // --- Public URLs ---
  {
    canonical: "BONDERY_PUBLIC_API_URL",
    description: "Public API base URL (no trailing /api)",
    exampleValue: "http://localhost:26631",
    group: "Public URLs",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api"), t("webapp"), t("chrome-extension"), t("mobile")],
  },
  {
    canonical: "BONDERY_PUBLIC_WEBAPP_URL",
    description: "Public webapp origin",
    exampleValue: "http://localhost:26632",
    group: "Public URLs",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [
      t("api"),
      t("webapp"),
      t("website"),
      t("chrome-extension"),
      t("supabase-db", "BONDERY_SUPABASE_WEBAPP_URL"),
      {
        deriveFrom: "BONDERY_PUBLIC_WEBAPP_URL",
        id: "supabase-db",
        runtimeName: "BONDERY_SUPABASE_WEBAPP_CALLBACK_URL",
        transform: "webapp-auth-callback",
      },
    ],
  },
  {
    canonical: "BONDERY_PUBLIC_WEBSITE_URL",
    description: "Public marketing website origin",
    exampleValue: "http://localhost:26630",
    group: "Public URLs",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api"), t("webapp"), t("website"), t("mobile")],
  },
  {
    canonical: "BONDERY_PUBLIC_EXTRA_ALLOWED_ORIGINS",
    description: "Comma-separated extra CORS origins (e.g. Expo web)",
    exampleValue: "http://localhost:26634",
    group: "Public URLs",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },

  // --- Supabase ---
  {
    canonical: "BONDERY_PUBLIC_SUPABASE_URL",
    description:
      "Supabase project URL (OAuth provider redirect_uri is derived as {url}/auth/v1/callback)",
    exampleValue: "http://127.0.0.1:54321",
    group: "Supabase",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [
      t("api"),
      t("webapp"),
      t("chrome-extension"),
      t("mobile"),
      {
        deriveFrom: "BONDERY_PUBLIC_SUPABASE_URL",
        id: "supabase-db",
        runtimeName: "BONDERY_SUPABASE_AUTH_CALLBACK_URL",
        transform: "supabase-auth-callback",
      },
    ],
  },
  {
    canonical: "BONDERY_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
    description: "Supabase publishable (anon) key",
    exampleValue: "sb_publishable_<your-publishable-key>",
    group: "Supabase",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api"), t("webapp"), t("mobile")],
  },
  {
    canonical: "BONDERY_PRIVATE_SUPABASE_SECRET_KEY",
    description: "Supabase secret (service role) key",
    exampleValue: "sb_secret_<your-secret-key>",
    group: "Supabase",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_SUPABASE_JWT_SIGNING_JWK",
    description: "Compact single-line JWT signing JWK JSON",
    exampleValue:
      '{"kty":"EC","kid":"<your-kid>","use":"sig","alg":"ES256","crv":"P-256","d":"<private-d>","x":"<public-x>","y":"<public-y>"}',
    group: "Supabase",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PUBLIC_SUPABASE_OAUTH_CLIENT_ID",
    description: "Chrome extension OAuth client id (Supabase Dashboard)",
    exampleValue: "",
    group: "Supabase",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("chrome-extension")],
  },

  // --- supabase-db auth (CLI substitution names) ---
  // BONDERY_SUPABASE_AUTH_CALLBACK_URL is derived from BONDERY_PUBLIC_SUPABASE_URL
  {
    canonical: "BONDERY_SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID",
    description: "GitHub OAuth client id for local Supabase Auth",
    exampleValue: "",
    group: "Supabase Auth (local)",
    requiredIn: [],
    secret: false,
    targets: [t("supabase-db")],
  },
  {
    canonical: "BONDERY_SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET",
    description: "GitHub OAuth client secret for local Supabase Auth",
    exampleValue: "",
    group: "Supabase Auth (local)",
    requiredIn: [],
    secret: true,
    targets: [t("supabase-db")],
  },
  {
    canonical: "BONDERY_SUPABASE_AUTH_EXTERNAL_LINKEDIN_CLIENT_ID",
    description: "LinkedIn OAuth client id for local Supabase Auth",
    exampleValue: "",
    group: "Supabase Auth (local)",
    requiredIn: [],
    secret: false,
    targets: [t("supabase-db")],
  },
  {
    canonical: "BONDERY_SUPABASE_AUTH_EXTERNAL_LINKEDIN_SECRET",
    description: "LinkedIn OAuth client secret for local Supabase Auth",
    exampleValue: "",
    group: "Supabase Auth (local)",
    requiredIn: [],
    secret: true,
    targets: [t("supabase-db")],
  },

  // --- API secrets ---
  {
    canonical: "BONDERY_PRIVATE_API_KEY_PEPPER",
    description: "Pepper for hashing API keys",
    exampleValue: "<your-api-key-pepper>",
    group: "API secrets",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_EMAIL_HOST",
    description: "SMTP host",
    exampleValue: "smtp.example.com",
    group: "Email",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_EMAIL_PORT",
    description: "SMTP port",
    exampleValue: "465",
    group: "Email",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_EMAIL_USER",
    description: "SMTP username",
    exampleValue: "robot@example.com",
    group: "Email",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_EMAIL_PASS",
    description: "SMTP password",
    exampleValue: "your-email-password",
    group: "Email",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_EMAIL_ADDRESS",
    description: "From address for transactional email",
    exampleValue: "robot@example.com",
    group: "Email",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_REDIS_URL",
    description: "Redis connection URL",
    exampleValue: "redis://127.0.0.1:26636",
    group: "Redis",
    requiredIn: ["production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_POLAR_ACCESS_TOKEN",
    description: "Polar.sh API access token",
    exampleValue: "<your-polar-access-token>",
    group: "Polar",
    requiredIn: ["production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_POLAR_WEBHOOK_SECRET",
    description: "Polar.sh webhook secret",
    exampleValue: "<your-polar-webhook-secret>",
    group: "Polar",
    requiredIn: ["production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PUBLIC_POLAR_ENVIRONMENT",
    description: "Polar environment (sandbox | production)",
    exampleValue: "sandbox",
    group: "Polar",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PUBLIC_POLAR_PRODUCT_ID",
    description: "Polar product id for checkout",
    exampleValue: "<your-polar-product-id>",
    group: "Polar",
    requiredIn: ["production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PUBLIC_MAPS_URL",
    description: "Mapy.com API base URL",
    exampleValue: "https://api.mapy.com",
    group: "Maps",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_MAPS_KEY",
    description: "Mapy.com API key",
    exampleValue: "<your-maps-api-key>",
    group: "Maps",
    requiredIn: [],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_ANTHROPIC_API_KEY",
    description: "Anthropic API key for AI features",
    exampleValue: "sk-ant-<your-anthropic-api-key>",
    group: "AI",
    requiredIn: [],
    secret: true,
    targets: [t("api")],
  },

  // --- Analytics ---
  {
    canonical: "BONDERY_PUBLIC_POSTHOG_KEY",
    description: "PostHog project API key (browser)",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: false,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_PUBLIC_POSTHOG_HOST",
    description: "PostHog host URL",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: false,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_PRIVATE_POSTHOG_KEY",
    description: "PostHog personal/project key for server-side capture (optional)",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: true,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_PRIVATE_POSTHOG_HOST",
    description: "PostHog host for server-side capture (optional)",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: true,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_PRIVATE_POSTHOG_API_SECRET",
    description: "PostHog personal API key for admin analytics queries (optional)",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_POSTHOG_PROJECT_ID",
    description: "PostHog project id for admin analytics queries (optional)",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "DO_NOT_TRACK",
    description: "Disable analytics / vendor telemetry when true",
    exampleValue: "true",
    group: "Analytics",
    requiredIn: [],
    secret: false,
    targets: [t("api"), t("webapp"), t("website")],
  },

  // --- Infra (optional local) ---
  {
    canonical: "BONDERY_INFRA_VERSION",
    description: "App version surfaced in webapp runtime config",
    exampleValue: "",
    group: "Infra",
    requiredIn: [],
    secret: false,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_INFRA_GIT_SHA",
    description: "Git SHA surfaced in webapp runtime config",
    exampleValue: "",
    group: "Infra",
    requiredIn: [],
    secret: false,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_INFRA_INTERNAL_API_URL",
    description: "Compose-internal API URL (production webapp only)",
    exampleValue: "",
    group: "Infra",
    requiredIn: [],
    secret: false,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_PUBLIC_SYNC_DEBUG",
    description: "Mobile sync debug logging (1/true)",
    exampleValue: "",
    group: "Mobile",
    requiredIn: [],
    secret: false,
    targets: [t("mobile")],
  },
];

/** System / pass-through vars always listed in turbo globalPassThroughEnv */
export const TURBO_SYSTEM_PASSTHROUGH = [
  "PATH",
  "WINDIR",
  "HOME",
  "USERPROFILE",
  "TMP",
  "TEMP",
  "TMPDIR",
  "NODE_ENV",
  "CI",
  "GITHUB_ACTIONS",
  "TURBO_TELEMETRY_DISABLED",
  "TURBO_TEAM",
  "TURBO_TOKEN",
  "npm_package_version",
  "METRO_MAX_WORKERS",
  "NGROK",
  "PORT",
  "LOG_LEVEL",
  "SYNC_WAKE_ENABLED",
  "NEXT_RUNTIME",
  "DO_NOT_TRACK",
  "NO_COLOR",
  "FORCE_COLOR",
] as const;

/** Ops secrets — GitHub Actions only; never written by `npm run env` */
export const OPS_ENV_VARS = [
  "BONDERY_OPS_CHROME_EXTENSION_ID",
  "BONDERY_OPS_CHROME_PUBLISHER_ID",
  "PRIVATE_CHROME_SERVICE_ACCOUNT_KEY_JSON",
  "PRIVATE_CHROME_PRIVATE_SIGNING_KEY",
  "BONDERY_OPS_DISCORD_WEBHOOK_URL",
  "BONDERY_OPS_GHCR_WRITE_TOKEN",
  "BONDERY_OPS_REDDIT_CLIENT_ID",
  "BONDERY_OPS_REDDIT_CLIENT_SECRET",
  "BONDERY_OPS_REDDIT_PASSWORD",
  "BONDERY_OPS_REDDIT_USERNAME",
  "BONDERY_OPS_TURBO_TEAM",
  "BONDERY_OPS_TURBO_TOKEN",
] as const;

export function applyTransform(transform: EnvTargetWrite["transform"], value: string): string {
  const base = value.replace(/\/$/, "");
  if (transform === "webapp-auth-callback") {
    return `${base}/auth/callback`;
  }
  if (transform === "supabase-auth-callback") {
    return `${base}/auth/v1/callback`;
  }
  return value;
}

export function getRequiredVarsForTarget(
  targetId: TargetId,
  environment: EnvEnvironment,
): string[] {
  const names = new Set<string>();
  for (const entry of ENV_MANIFEST) {
    if (!entry.requiredIn.includes(environment)) {
      continue;
    }
    for (const target of entry.targets) {
      if (target.id !== targetId) {
        continue;
      }
      names.add(target.runtimeName ?? entry.canonical);
    }
  }
  return [...names].sort();
}

export function getRuntimeNamesForTarget(targetId: TargetId): string[] {
  const names = new Set<string>();
  for (const entry of ENV_MANIFEST) {
    if (entry.turboAffectsCache === false) {
      continue;
    }
    for (const target of entry.targets) {
      if (target.id !== targetId) {
        continue;
      }
      names.add(target.runtimeName ?? entry.canonical);
    }
  }
  return [...names].sort();
}

export function getAllRuntimeNames(): string[] {
  const names = new Set<string>();
  for (const entry of ENV_MANIFEST) {
    names.add(entry.canonical);
    for (const target of entry.targets) {
      names.add(target.runtimeName ?? entry.canonical);
    }
  }
  for (const name of OPS_ENV_VARS) {
    names.add(name);
  }
  return [...names].sort();
}

export function resolveCanonicalValue(
  rootEnv: Record<string, string>,
  entry: EnvVarDef,
  target: EnvTargetWrite,
): string | undefined {
  if (target.deriveFrom) {
    const source = rootEnv[target.deriveFrom];
    if (source === undefined || source === "") {
      return undefined;
    }
    return applyTransform(target.transform, source);
  }
  const value = rootEnv[entry.canonical];
  if (value === undefined) {
    return undefined;
  }
  return value;
}
