/**
 * Supported languages configuration
 */

export interface LanguageData {
  value: string; // Language code (e.g., 'en', 'cs')
  label: string; // Display name
  flag: string; // ISO country code for flag
  nativeName: string; // Native language name
}

// App-supported languages (for settings/translations)
export const APP_LANGUAGES_DATA: LanguageData[] = [
  {
    value: "en",
    label: "English",
    flag: "gb",
    nativeName: "English",
  },
  {
    value: "cs",
    label: "Czech",
    flag: "cz",
    nativeName: "Čeština",
  },
];

// World languages for contact language preferences
export const WORLD_LANGUAGES_DATA: LanguageData[] = [
  { value: "ab", label: "Abkhazian", flag: "ge", nativeName: "аҧсуа бызшәа" },
  { value: "aa", label: "Afar", flag: "et", nativeName: "Afaraf" },
  { value: "af", label: "Afrikaans", flag: "za", nativeName: "Afrikaans" },
  { value: "ak", label: "Akan", flag: "gh", nativeName: "Akan" },
  { value: "sq", label: "Albanian", flag: "al", nativeName: "Shqip" },
  { value: "am", label: "Amharic", flag: "et", nativeName: "አማርኛ" },
  { value: "ar", label: "Arabic", flag: "sa", nativeName: "العربية" },
  { value: "an", label: "Aragonese", flag: "es", nativeName: "aragonés" },
  { value: "hy", label: "Armenian", flag: "am", nativeName: "Հայերեն" },
  { value: "as", label: "Assamese", flag: "in", nativeName: "অসমীয়া" },
  { value: "av", label: "Avaric", flag: "ru", nativeName: "авар мацӀ" },
  { value: "ae", label: "Avestan", flag: "ir", nativeName: "avesta" },
  { value: "ay", label: "Aymara", flag: "bo", nativeName: "aymar aru" },
  { value: "az", label: "Azerbaijani", flag: "az", nativeName: "azərbaycan dili" },
  { value: "bm", label: "Bambara", flag: "ml", nativeName: "bamanankan" },
  { value: "ba", label: "Bashkir", flag: "ru", nativeName: "башҡорт теле" },
  { value: "eu", label: "Basque", flag: "es", nativeName: "euskera" },
  { value: "be", label: "Belarusian", flag: "by", nativeName: "беларуская мова" },
  { value: "bn", label: "Bengali", flag: "bd", nativeName: "বাংলা" },
  { value: "bh", label: "Bihari languages", flag: "in", nativeName: "भोजपुरी" },
  { value: "bi", label: "Bislama", flag: "vu", nativeName: "Bislama" },
  { value: "bs", label: "Bosnian", flag: "ba", nativeName: "bosanski jezik" },
  { value: "br", label: "Breton", flag: "fr", nativeName: "brezhoneg" },
  { value: "bg", label: "Bulgarian", flag: "bg", nativeName: "български език" },
  { value: "my", label: "Burmese", flag: "mm", nativeName: "ဗမာစာ" },
  { value: "ca", label: "Catalan", flag: "es", nativeName: "català" },
  { value: "ch", label: "Chamorro", flag: "gu", nativeName: "Chamoru" },
  { value: "ce", label: "Chechen", flag: "ru", nativeName: "нохчийн мотт" },
  { value: "ny", label: "Chichewa", flag: "mw", nativeName: "chiCheŵa" },
  { value: "zh", label: "Chinese", flag: "cn", nativeName: "中文" },
  { value: "cv", label: "Chuvash", flag: "ru", nativeName: "чӑваш чӗлхи" },
  { value: "kw", label: "Cornish", flag: "gb", nativeName: "Kernewek" },
  { value: "co", label: "Corsican", flag: "fr", nativeName: "corsu" },
  { value: "cr", label: "Cree", flag: "ca", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ" },
  { value: "hr", label: "Croatian", flag: "hr", nativeName: "hrvatski jezik" },
  { value: "cs", label: "Czech", flag: "cz", nativeName: "čeština" },
  { value: "da", label: "Danish", flag: "dk", nativeName: "dansk" },
  { value: "dv", label: "Divehi", flag: "mv", nativeName: "ދިވެހި" },
  { value: "nl", label: "Dutch", flag: "nl", nativeName: "Nederlands" },
  { value: "dz", label: "Dzongkha", flag: "bt", nativeName: "རྫོང་ཁ" },
  { value: "en", label: "English", flag: "gb", nativeName: "English" },
  { value: "eo", label: "Esperanto", flag: "eo", nativeName: "Esperanto" },
  { value: "et", label: "Estonian", flag: "ee", nativeName: "eesti" },
  { value: "ee", label: "Ewe", flag: "gh", nativeName: "Eʋegbe" },
  { value: "fo", label: "Faroese", flag: "fo", nativeName: "føroyskt" },
  { value: "fj", label: "Fijian", flag: "fj", nativeName: "vosa Vakaviti" },
  { value: "fi", label: "Finnish", flag: "fi", nativeName: "suomi" },
  { value: "fr", label: "French", flag: "fr", nativeName: "français" },
  { value: "ff", label: "Fulah", flag: "sn", nativeName: "Fulfulde" },
  { value: "gl", label: "Galician", flag: "es", nativeName: "galego" },
  { value: "ka", label: "Georgian", flag: "ge", nativeName: "ქართული" },
  { value: "de", label: "German", flag: "de", nativeName: "Deutsch" },
  { value: "el", label: "Greek", flag: "gr", nativeName: "ελληνικά" },
  { value: "gn", label: "Guaraní", flag: "py", nativeName: "Avañe'ẽ" },
  { value: "gu", label: "Gujarati", flag: "in", nativeName: "ગુજરાતી" },
  { value: "ht", label: "Haitian", flag: "ht", nativeName: "Kreyòl ayisyen" },
  { value: "ha", label: "Hausa", flag: "ng", nativeName: "Hausa" },
  { value: "he", label: "Hebrew", flag: "il", nativeName: "עברית" },
  { value: "hz", label: "Herero", flag: "na", nativeName: "Otjiherero" },
  { value: "hi", label: "Hindi", flag: "in", nativeName: "हिन्दी" },
  { value: "ho", label: "Hiri Motu", flag: "pg", nativeName: "Hiri Motu" },
  { value: "hu", label: "Hungarian", flag: "hu", nativeName: "magyar" },
  { value: "ia", label: "Interlingua", flag: "ia", nativeName: "Interlingua" },
  { value: "id", label: "Indonesian", flag: "id", nativeName: "Bahasa Indonesia" },
  { value: "ie", label: "Interlingue", flag: "ie", nativeName: "Interlingue" },
  { value: "ga", label: "Irish", flag: "ie", nativeName: "Gaeilge" },
  { value: "ig", label: "Igbo", flag: "ng", nativeName: "Asụsụ Igbo" },
  { value: "ik", label: "Inupiaq", flag: "us", nativeName: "Iñupiaq" },
  { value: "io", label: "Ido", flag: "io", nativeName: "Ido" },
  { value: "is", label: "Icelandic", flag: "is", nativeName: "Íslenska" },
  { value: "it", label: "Italian", flag: "it", nativeName: "italiano" },
  { value: "iu", label: "Inuktitut", flag: "ca", nativeName: "ᐃᓄᒃᑎᑐᑦ" },
  { value: "ja", label: "Japanese", flag: "jp", nativeName: "日本語" },
  { value: "jv", label: "Javanese", flag: "id", nativeName: "basa Jawa" },
  { value: "kl", label: "Kalaallisut", flag: "gl", nativeName: "kalaallisut" },
  { value: "kn", label: "Kannada", flag: "in", nativeName: "ಕನ್ನಡ" },
  { value: "kr", label: "Kanuri", flag: "ng", nativeName: "Kanuri" },
  { value: "ks", label: "Kashmiri", flag: "in", nativeName: "कश्मीरी" },
  { value: "kk", label: "Kazakh", flag: "kz", nativeName: "қазақ тілі" },
  { value: "km", label: "Central Khmer", flag: "kh", nativeName: "ខ្មែរ" },
  { value: "ki", label: "Kikuyu", flag: "ke", nativeName: "Gĩkũyũ" },
  { value: "rw", label: "Kinyarwanda", flag: "rw", nativeName: "Ikinyarwanda" },
  { value: "ky", label: "Kirghiz", flag: "kg", nativeName: "Кыргызча" },
  { value: "kv", label: "Komi", flag: "ru", nativeName: "коми кыв" },
  { value: "kg", label: "Kongo", flag: "cg", nativeName: "KiKongo" },
  { value: "ko", label: "Korean", flag: "kr", nativeName: "한국어" },
  { value: "ku", label: "Kurdish", flag: "iq", nativeName: "Kurdî" },
  { value: "kj", label: "Kuanyama", flag: "ao", nativeName: "Kuanyama" },
  { value: "la", label: "Latin", flag: "va", nativeName: "latine" },
  { value: "lb", label: "Luxembourgish", flag: "lu", nativeName: "Lëtzebuergesch" },
  { value: "lg", label: "Ganda", flag: "ug", nativeName: "Luganda" },
  { value: "li", label: "Limburgan", flag: "nl", nativeName: "Limburgs" },
  { value: "ln", label: "Lingala", flag: "cd", nativeName: "Lingála" },
  { value: "lo", label: "Lao", flag: "la", nativeName: "ພາສາລາວ" },
  { value: "lt", label: "Lithuanian", flag: "lt", nativeName: "lietuvių kalba" },
  { value: "lu", label: "Luba-Katanga", flag: "cd", nativeName: "Tshiluba" },
  { value: "lv", label: "Latvian", flag: "lv", nativeName: "latviešu valoda" },
  { value: "gv", label: "Manx", flag: "im", nativeName: "Gaelg" },
  { value: "mk", label: "Macedonian", flag: "mk", nativeName: "македонски јазик" },
  { value: "mg", label: "Malagasy", flag: "mg", nativeName: "fiteny malagasy" },
  { value: "ms", label: "Malay", flag: "my", nativeName: "bahasa Melayu" },
  { value: "ml", label: "Malayalam", flag: "in", nativeName: "മലയാളം" },
  { value: "mt", label: "Maltese", flag: "mt", nativeName: "Malti" },
  { value: "mi", label: "Māori", flag: "nz", nativeName: "te reo Māori" },
  { value: "mr", label: "Marathi", flag: "in", nativeName: "मराठी" },
  { value: "mh", label: "Marshallese", flag: "mh", nativeName: "Kajin M̧ajeļ" },
  { value: "mn", label: "Mongolian", flag: "mn", nativeName: "Монгол хэл" },
  { value: "na", label: "Nauru", flag: "nr", nativeName: "Dorerin Naoero" },
  { value: "nv", label: "Navajo", flag: "us", nativeName: "Diné bizaad" },
  { value: "nd", label: "North Ndebele", flag: "zw", nativeName: "isiNdebele" },
  { value: "ne", label: "Nepali", flag: "np", nativeName: "नेपाली" },
  { value: "ng", label: "Ndonga", flag: "na", nativeName: "Owambo" },
  { value: "nb", label: "Norwegian Bokmål", flag: "no", nativeName: "Norsk bokmål" },
  { value: "nn", label: "Norwegian Nynorsk", flag: "no", nativeName: "Norsk nynorsk" },
  { value: "no", label: "Norwegian", flag: "no", nativeName: "Norsk" },
  { value: "ii", label: "Nuosu", flag: "cn", nativeName: "ꆈꌠ꒿ Nuosuhxop" },
  { value: "nr", label: "South Ndebele", flag: "za", nativeName: "isiNdebele" },
  { value: "oc", label: "Occitan", flag: "fr", nativeName: "occitan" },
  { value: "oj", label: "Ojibwa", flag: "ca", nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ" },
  { value: "cu", label: "Church Slavic", flag: "bg", nativeName: "ѩзыкъ словѣньскъ" },
  { value: "om", label: "Oromo", flag: "et", nativeName: "Afaan Oromoo" },
  { value: "or", label: "Oriya", flag: "in", nativeName: "ଓଡ଼ିଆ" },
  { value: "os", label: "Ossetian", flag: "ge", nativeName: "ирон æвзаг" },
  { value: "pa", label: "Panjabi", flag: "in", nativeName: "ਪੰਜਾਬੀ" },
  { value: "pi", label: "Pali", flag: "in", nativeName: "पाऴि" },
  { value: "fa", label: "Persian", flag: "ir", nativeName: "فارسی" },
  { value: "pl", label: "Polish", flag: "pl", nativeName: "język polski" },
  { value: "ps", label: "Pashto", flag: "af", nativeName: "پښتو" },
  { value: "pt", label: "Portuguese", flag: "pt", nativeName: "português" },
  { value: "qu", label: "Quechua", flag: "pe", nativeName: "Runa Simi" },
  { value: "rm", label: "Romansh", flag: "ch", nativeName: "rumantsch grischun" },
  { value: "rn", label: "Rundi", flag: "bi", nativeName: "Ikirundi" },
  { value: "ro", label: "Romanian", flag: "ro", nativeName: "limba română" },
  { value: "ru", label: "Russian", flag: "ru", nativeName: "русский" },
  { value: "sa", label: "Sanskrit", flag: "in", nativeName: "संस्कृतम्" },
  { value: "sc", label: "Sardinian", flag: "it", nativeName: "sardu" },
  { value: "sd", label: "Sindhi", flag: "pk", nativeName: "सिन्धी" },
  { value: "se", label: "Northern Sami", flag: "no", nativeName: "Davvisámegiella" },
  { value: "sm", label: "Samoan", flag: "ws", nativeName: "gagana fa'a Samoa" },
  { value: "sg", label: "Sango", flag: "cf", nativeName: "yângâ tî sängö" },
  { value: "sr", label: "Serbian", flag: "rs", nativeName: "српски језик" },
  { value: "gd", label: "Gaelic", flag: "gb", nativeName: "Gàidhlig" },
  { value: "sn", label: "Shona", flag: "zw", nativeName: "chiShona" },
  { value: "si", label: "Sinhala", flag: "lk", nativeName: "සිංහල" },
  { value: "sk", label: "Slovak", flag: "sk", nativeName: "slovenčina" },
  { value: "sl", label: "Slovenian", flag: "si", nativeName: "slovenski jezik" },
  { value: "so", label: "Somali", flag: "so", nativeName: "Soomaaliga" },
  { value: "st", label: "Southern Sotho", flag: "ls", nativeName: "Sesotho" },
  { value: "es", label: "Spanish", flag: "es", nativeName: "español" },
  { value: "su", label: "Sundanese", flag: "id", nativeName: "Basa Sunda" },
  { value: "sw", label: "Swahili", flag: "ke", nativeName: "Kiswahili" },
  { value: "ss", label: "Swati", flag: "sz", nativeName: "SiSwati" },
  { value: "sv", label: "Swedish", flag: "se", nativeName: "svenska" },
  { value: "ta", label: "Tamil", flag: "in", nativeName: "தமிழ்" },
  { value: "te", label: "Telugu", flag: "in", nativeName: "తెలుగు" },
  { value: "tg", label: "Tajik", flag: "tj", nativeName: "тоҷикӣ" },
  { value: "th", label: "Thai", flag: "th", nativeName: "ไทย" },
  { value: "ti", label: "Tigrinya", flag: "er", nativeName: "ትግርኛ" },
  { value: "bo", label: "Tibetan", flag: "cn", nativeName: "བོད་ཡིག" },
  { value: "tk", label: "Turkmen", flag: "tm", nativeName: "Türkmen" },
  { value: "tl", label: "Tagalog", flag: "ph", nativeName: "Wikang Tagalog" },
  { value: "tn", label: "Tswana", flag: "bw", nativeName: "Setswana" },
  { value: "to", label: "Tonga", flag: "to", nativeName: "faka Tonga" },
  { value: "tr", label: "Turkish", flag: "tr", nativeName: "Türkçe" },
  { value: "ts", label: "Tsonga", flag: "za", nativeName: "Xitsonga" },
  { value: "tt", label: "Tatar", flag: "ru", nativeName: "татар теле" },
  { value: "tw", label: "Twi", flag: "gh", nativeName: "Twi" },
  { value: "ty", label: "Tahitian", flag: "pf", nativeName: "Reo Tahiti" },
  { value: "ug", label: "Uighur", flag: "cn", nativeName: "Uyƣurqə" },
  { value: "uk", label: "Ukrainian", flag: "ua", nativeName: "українська мова" },
  { value: "ur", label: "Urdu", flag: "pk", nativeName: "اردو" },
  { value: "uz", label: "Uzbek", flag: "uz", nativeName: "O'zbek" },
  { value: "ve", label: "Venda", flag: "za", nativeName: "Tshivenḓa" },
  { value: "vi", label: "Vietnamese", flag: "vn", nativeName: "Tiếng Việt" },
  { value: "vo", label: "Volapük", flag: "vo", nativeName: "Volapük" },
  { value: "wa", label: "Walloon", flag: "be", nativeName: "walon" },
  { value: "cy", label: "Welsh", flag: "gb", nativeName: "Cymraeg" },
  { value: "wo", label: "Wolof", flag: "sn", nativeName: "Wollof" },
  { value: "fy", label: "Western Frisian", flag: "nl", nativeName: "Frysk" },
  { value: "xh", label: "Xhosa", flag: "za", nativeName: "isiXhosa" },
  { value: "yi", label: "Yiddish", flag: "il", nativeName: "ייִדיש" },
  { value: "yo", label: "Yoruba", flag: "ng", nativeName: "Yorùbá" },
  { value: "za", label: "Zhuang", flag: "cn", nativeName: "Saɯ cueŋƅ" },
  { value: "zu", label: "Zulu", flag: "za", nativeName: "isiZulu" },
];

// Default export for backward compatibility
export const LANGUAGES_DATA = APP_LANGUAGES_DATA;
