export interface TimezoneData {
  value: string; // IANA timezone identifier
  city: string; // City name
  country: string; // Country name
  continent: string; // Continent for grouping
  flag: string; // ISO 3166-1 alpha-2 country code
  offset: number; // UTC offset in minutes
}

export const TIMEZONES_DATA: TimezoneData[] = [
  // UTC
  {
    value: "UTC",
    city: "UTC",
    country: "Coordinated Universal Time",
    continent: "UTC",
    flag: "",
    offset: 0,
  },

  // Africa
  {
    value: "Africa/Abidjan",
    city: "Abidjan",
    country: "Côte d'Ivoire",
    continent: "Africa",
    flag: "ci",
    offset: 0,
  },
  {
    value: "Africa/Accra",
    city: "Accra",
    country: "Ghana",
    continent: "Africa",
    flag: "gh",
    offset: 0,
  },
  {
    value: "Africa/Addis_Ababa",
    city: "Addis Ababa",
    country: "Ethiopia",
    continent: "Africa",
    flag: "et",
    offset: 180,
  },
  {
    value: "Africa/Algiers",
    city: "Algiers",
    country: "Algeria",
    continent: "Africa",
    flag: "dz",
    offset: 60,
  },
  {
    value: "Africa/Cairo",
    city: "Cairo",
    country: "Egypt",
    continent: "Africa",
    flag: "eg",
    offset: 120,
  },
  {
    value: "Africa/Casablanca",
    city: "Casablanca",
    country: "Morocco",
    continent: "Africa",
    flag: "ma",
    offset: 60,
  },
  {
    value: "Africa/Dakar",
    city: "Dakar",
    country: "Senegal",
    continent: "Africa",
    flag: "sn",
    offset: 0,
  },
  {
    value: "Africa/Johannesburg",
    city: "Johannesburg",
    country: "South Africa",
    continent: "Africa",
    flag: "za",
    offset: 120,
  },
  {
    value: "Africa/Khartoum",
    city: "Khartoum",
    country: "Sudan",
    continent: "Africa",
    flag: "sd",
    offset: 120,
  },
  {
    value: "Africa/Lagos",
    city: "Lagos",
    country: "Nigeria",
    continent: "Africa",
    flag: "ng",
    offset: 60,
  },
  {
    value: "Africa/Nairobi",
    city: "Nairobi",
    country: "Kenya",
    continent: "Africa",
    flag: "ke",
    offset: 180,
  },
  {
    value: "Africa/Tunis",
    city: "Tunis",
    country: "Tunisia",
    continent: "Africa",
    flag: "tn",
    offset: 60,
  },
  {
    value: "Africa/Tripoli",
    city: "Tripoli",
    country: "Libya",
    continent: "Africa",
    flag: "ly",
    offset: 120,
  },

  // Americas
  {
    value: "America/Anchorage",
    city: "Anchorage",
    country: "USA (Alaska)",
    continent: "Americas",
    flag: "us",
    offset: -540,
  },
  {
    value: "America/Argentina/Buenos_Aires",
    city: "Buenos Aires",
    country: "Argentina",
    continent: "Americas",
    flag: "ar",
    offset: -180,
  },
  {
    value: "America/Asuncion",
    city: "Asunción",
    country: "Paraguay",
    continent: "Americas",
    flag: "py",
    offset: -240,
  },
  {
    value: "America/Bogota",
    city: "Bogotá",
    country: "Colombia",
    continent: "Americas",
    flag: "co",
    offset: -300,
  },
  {
    value: "America/Caracas",
    city: "Caracas",
    country: "Venezuela",
    continent: "Americas",
    flag: "ve",
    offset: -240,
  },
  {
    value: "America/Chicago",
    city: "Chicago",
    country: "USA (Central)",
    continent: "Americas",
    flag: "us",
    offset: -360,
  },
  {
    value: "America/Denver",
    city: "Denver",
    country: "USA (Mountain)",
    continent: "Americas",
    flag: "us",
    offset: -420,
  },
  {
    value: "America/Guatemala",
    city: "Guatemala City",
    country: "Guatemala",
    continent: "Americas",
    flag: "gt",
    offset: -360,
  },
  {
    value: "America/Halifax",
    city: "Halifax",
    country: "Canada",
    continent: "Americas",
    flag: "ca",
    offset: -240,
  },
  {
    value: "America/Havana",
    city: "Havana",
    country: "Cuba",
    continent: "Americas",
    flag: "cu",
    offset: -300,
  },
  {
    value: "America/Lima",
    city: "Lima",
    country: "Peru",
    continent: "Americas",
    flag: "pe",
    offset: -300,
  },
  {
    value: "America/Los_Angeles",
    city: "Los Angeles",
    country: "USA (Pacific)",
    continent: "Americas",
    flag: "us",
    offset: -480,
  },
  {
    value: "America/Managua",
    city: "Managua",
    country: "Nicaragua",
    continent: "Americas",
    flag: "ni",
    offset: -360,
  },
  {
    value: "America/Mexico_City",
    city: "Mexico City",
    country: "Mexico",
    continent: "Americas",
    flag: "mx",
    offset: -360,
  },
  {
    value: "America/Montevideo",
    city: "Montevideo",
    country: "Uruguay",
    continent: "Americas",
    flag: "uy",
    offset: -180,
  },
  {
    value: "America/New_York",
    city: "New York",
    country: "USA (Eastern)",
    continent: "Americas",
    flag: "us",
    offset: -300,
  },
  {
    value: "America/Panama",
    city: "Panama City",
    country: "Panama",
    continent: "Americas",
    flag: "pa",
    offset: -300,
  },
  {
    value: "America/Phoenix",
    city: "Phoenix",
    country: "USA (Arizona)",
    continent: "Americas",
    flag: "us",
    offset: -420,
  },
  {
    value: "America/Regina",
    city: "Regina",
    country: "Canada",
    continent: "Americas",
    flag: "ca",
    offset: -360,
  },
  {
    value: "America/Santiago",
    city: "Santiago",
    country: "Chile",
    continent: "Americas",
    flag: "cl",
    offset: -240,
  },
  {
    value: "America/Sao_Paulo",
    city: "São Paulo",
    country: "Brazil",
    continent: "Americas",
    flag: "br",
    offset: -180,
  },
  {
    value: "America/St_Johns",
    city: "St. John's",
    country: "Canada",
    continent: "Americas",
    flag: "ca",
    offset: -210,
  },
  {
    value: "America/Toronto",
    city: "Toronto",
    country: "Canada",
    continent: "Americas",
    flag: "ca",
    offset: -300,
  },
  {
    value: "America/Vancouver",
    city: "Vancouver",
    country: "Canada",
    continent: "Americas",
    flag: "ca",
    offset: -480,
  },

  // Asia
  {
    value: "Asia/Almaty",
    city: "Almaty",
    country: "Kazakhstan",
    continent: "Asia",
    flag: "kz",
    offset: 360,
  },
  {
    value: "Asia/Amman",
    city: "Amman",
    country: "Jordan",
    continent: "Asia",
    flag: "jo",
    offset: 120,
  },
  {
    value: "Asia/Baghdad",
    city: "Baghdad",
    country: "Iraq",
    continent: "Asia",
    flag: "iq",
    offset: 180,
  },
  {
    value: "Asia/Baku",
    city: "Baku",
    country: "Azerbaijan",
    continent: "Asia",
    flag: "az",
    offset: 240,
  },
  {
    value: "Asia/Bangkok",
    city: "Bangkok",
    country: "Thailand",
    continent: "Asia",
    flag: "th",
    offset: 420,
  },
  {
    value: "Asia/Beirut",
    city: "Beirut",
    country: "Lebanon",
    continent: "Asia",
    flag: "lb",
    offset: 120,
  },
  {
    value: "Asia/Colombo",
    city: "Colombo",
    country: "Sri Lanka",
    continent: "Asia",
    flag: "lk",
    offset: 330,
  },
  {
    value: "Asia/Damascus",
    city: "Damascus",
    country: "Syria",
    continent: "Asia",
    flag: "sy",
    offset: 120,
  },
  {
    value: "Asia/Dhaka",
    city: "Dhaka",
    country: "Bangladesh",
    continent: "Asia",
    flag: "bd",
    offset: 360,
  },
  {
    value: "Asia/Dubai",
    city: "Dubai",
    country: "UAE",
    continent: "Asia",
    flag: "ae",
    offset: 240,
  },
  {
    value: "Asia/Hong_Kong",
    city: "Hong Kong",
    country: "Hong Kong",
    continent: "Asia",
    flag: "hk",
    offset: 480,
  },
  {
    value: "Asia/Jakarta",
    city: "Jakarta",
    country: "Indonesia",
    continent: "Asia",
    flag: "id",
    offset: 420,
  },
  {
    value: "Asia/Jerusalem",
    city: "Jerusalem",
    country: "Israel",
    continent: "Asia",
    flag: "il",
    offset: 120,
  },
  {
    value: "Asia/Kabul",
    city: "Kabul",
    country: "Afghanistan",
    continent: "Asia",
    flag: "af",
    offset: 270,
  },
  {
    value: "Asia/Karachi",
    city: "Karachi",
    country: "Pakistan",
    continent: "Asia",
    flag: "pk",
    offset: 300,
  },
  {
    value: "Asia/Kathmandu",
    city: "Kathmandu",
    country: "Nepal",
    continent: "Asia",
    flag: "np",
    offset: 345,
  },
  {
    value: "Asia/Kolkata",
    city: "Kolkata",
    country: "India",
    continent: "Asia",
    flag: "in",
    offset: 330,
  },
  {
    value: "Asia/Kuala_Lumpur",
    city: "Kuala Lumpur",
    country: "Malaysia",
    continent: "Asia",
    flag: "my",
    offset: 480,
  },
  {
    value: "Asia/Kuwait",
    city: "Kuwait City",
    country: "Kuwait",
    continent: "Asia",
    flag: "kw",
    offset: 180,
  },
  {
    value: "Asia/Manila",
    city: "Manila",
    country: "Philippines",
    continent: "Asia",
    flag: "ph",
    offset: 480,
  },
  {
    value: "Asia/Muscat",
    city: "Muscat",
    country: "Oman",
    continent: "Asia",
    flag: "om",
    offset: 240,
  },
  {
    value: "Asia/Riyadh",
    city: "Riyadh",
    country: "Saudi Arabia",
    continent: "Asia",
    flag: "sa",
    offset: 180,
  },
  {
    value: "Asia/Seoul",
    city: "Seoul",
    country: "South Korea",
    continent: "Asia",
    flag: "kr",
    offset: 540,
  },
  {
    value: "Asia/Shanghai",
    city: "Shanghai",
    country: "China",
    continent: "Asia",
    flag: "cn",
    offset: 480,
  },
  {
    value: "Asia/Singapore",
    city: "Singapore",
    country: "Singapore",
    continent: "Asia",
    flag: "sg",
    offset: 480,
  },
  {
    value: "Asia/Taipei",
    city: "Taipei",
    country: "Taiwan",
    continent: "Asia",
    flag: "tw",
    offset: 480,
  },
  {
    value: "Asia/Tashkent",
    city: "Tashkent",
    country: "Uzbekistan",
    continent: "Asia",
    flag: "uz",
    offset: 300,
  },
  {
    value: "Asia/Tehran",
    city: "Tehran",
    country: "Iran",
    continent: "Asia",
    flag: "ir",
    offset: 210,
  },
  {
    value: "Asia/Tokyo",
    city: "Tokyo",
    country: "Japan",
    continent: "Asia",
    flag: "jp",
    offset: 540,
  },
  {
    value: "Asia/Ulaanbaatar",
    city: "Ulaanbaatar",
    country: "Mongolia",
    continent: "Asia",
    flag: "mn",
    offset: 480,
  },
  {
    value: "Asia/Yangon",
    city: "Yangon",
    country: "Myanmar",
    continent: "Asia",
    flag: "mm",
    offset: 390,
  },
  {
    value: "Asia/Yerevan",
    city: "Yerevan",
    country: "Armenia",
    continent: "Asia",
    flag: "am",
    offset: 240,
  },

  // Europe
  {
    value: "Europe/Amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    continent: "Europe",
    flag: "nl",
    offset: 60,
  },
  {
    value: "Europe/Athens",
    city: "Athens",
    country: "Greece",
    continent: "Europe",
    flag: "gr",
    offset: 120,
  },
  {
    value: "Europe/Belgrade",
    city: "Belgrade",
    country: "Serbia",
    continent: "Europe",
    flag: "rs",
    offset: 60,
  },
  {
    value: "Europe/Berlin",
    city: "Berlin",
    country: "Germany",
    continent: "Europe",
    flag: "de",
    offset: 60,
  },
  {
    value: "Europe/Bratislava",
    city: "Bratislava",
    country: "Slovakia",
    continent: "Europe",
    flag: "sk",
    offset: 60,
  },
  {
    value: "Europe/Brussels",
    city: "Brussels",
    country: "Belgium",
    continent: "Europe",
    flag: "be",
    offset: 60,
  },
  {
    value: "Europe/Bucharest",
    city: "Bucharest",
    country: "Romania",
    continent: "Europe",
    flag: "ro",
    offset: 120,
  },
  {
    value: "Europe/Budapest",
    city: "Budapest",
    country: "Hungary",
    continent: "Europe",
    flag: "hu",
    offset: 60,
  },
  {
    value: "Europe/Copenhagen",
    city: "Copenhagen",
    country: "Denmark",
    continent: "Europe",
    flag: "dk",
    offset: 60,
  },
  {
    value: "Europe/Dublin",
    city: "Dublin",
    country: "Ireland",
    continent: "Europe",
    flag: "ie",
    offset: 0,
  },
  {
    value: "Europe/Helsinki",
    city: "Helsinki",
    country: "Finland",
    continent: "Europe",
    flag: "fi",
    offset: 120,
  },
  {
    value: "Europe/Istanbul",
    city: "Istanbul",
    country: "Turkey",
    continent: "Europe",
    flag: "tr",
    offset: 180,
  },
  {
    value: "Europe/Kyiv",
    city: "Kyiv",
    country: "Ukraine",
    continent: "Europe",
    flag: "ua",
    offset: 120,
  },
  {
    value: "Europe/Lisbon",
    city: "Lisbon",
    country: "Portugal",
    continent: "Europe",
    flag: "pt",
    offset: 0,
  },
  {
    value: "Europe/Ljubljana",
    city: "Ljubljana",
    country: "Slovenia",
    continent: "Europe",
    flag: "si",
    offset: 60,
  },
  {
    value: "Europe/London",
    city: "London",
    country: "United Kingdom",
    continent: "Europe",
    flag: "gb",
    offset: 0,
  },
  {
    value: "Europe/Madrid",
    city: "Madrid",
    country: "Spain",
    continent: "Europe",
    flag: "es",
    offset: 60,
  },
  {
    value: "Europe/Moscow",
    city: "Moscow",
    country: "Russia",
    continent: "Europe",
    flag: "ru",
    offset: 180,
  },
  {
    value: "Europe/Oslo",
    city: "Oslo",
    country: "Norway",
    continent: "Europe",
    flag: "no",
    offset: 60,
  },
  {
    value: "Europe/Paris",
    city: "Paris",
    country: "France",
    continent: "Europe",
    flag: "fr",
    offset: 60,
  },
  {
    value: "Europe/Prague",
    city: "Prague",
    country: "Czech Republic",
    continent: "Europe",
    flag: "cz",
    offset: 60,
  },
  {
    value: "Europe/Riga",
    city: "Riga",
    country: "Latvia",
    continent: "Europe",
    flag: "lv",
    offset: 120,
  },
  {
    value: "Europe/Rome",
    city: "Rome",
    country: "Italy",
    continent: "Europe",
    flag: "it",
    offset: 60,
  },
  {
    value: "Europe/Sofia",
    city: "Sofia",
    country: "Bulgaria",
    continent: "Europe",
    flag: "bg",
    offset: 120,
  },
  {
    value: "Europe/Stockholm",
    city: "Stockholm",
    country: "Sweden",
    continent: "Europe",
    flag: "se",
    offset: 60,
  },
  {
    value: "Europe/Tallinn",
    city: "Tallinn",
    country: "Estonia",
    continent: "Europe",
    flag: "ee",
    offset: 120,
  },
  {
    value: "Europe/Vienna",
    city: "Vienna",
    country: "Austria",
    continent: "Europe",
    flag: "at",
    offset: 60,
  },
  {
    value: "Europe/Vilnius",
    city: "Vilnius",
    country: "Lithuania",
    continent: "Europe",
    flag: "lt",
    offset: 120,
  },
  {
    value: "Europe/Warsaw",
    city: "Warsaw",
    country: "Poland",
    continent: "Europe",
    flag: "pl",
    offset: 60,
  },
  {
    value: "Europe/Zagreb",
    city: "Zagreb",
    country: "Croatia",
    continent: "Europe",
    flag: "hr",
    offset: 60,
  },
  {
    value: "Europe/Zurich",
    city: "Zurich",
    country: "Switzerland",
    continent: "Europe",
    flag: "ch",
    offset: 60,
  },

  // Oceania
  {
    value: "Australia/Adelaide",
    city: "Adelaide",
    country: "Australia",
    continent: "Oceania",
    flag: "au",
    offset: 570,
  },
  {
    value: "Australia/Brisbane",
    city: "Brisbane",
    country: "Australia",
    continent: "Oceania",
    flag: "au",
    offset: 600,
  },
  {
    value: "Australia/Darwin",
    city: "Darwin",
    country: "Australia",
    continent: "Oceania",
    flag: "au",
    offset: 570,
  },
  {
    value: "Australia/Hobart",
    city: "Hobart",
    country: "Australia",
    continent: "Oceania",
    flag: "au",
    offset: 600,
  },
  {
    value: "Australia/Melbourne",
    city: "Melbourne",
    country: "Australia",
    continent: "Oceania",
    flag: "au",
    offset: 600,
  },
  {
    value: "Australia/Perth",
    city: "Perth",
    country: "Australia",
    continent: "Oceania",
    flag: "au",
    offset: 480,
  },
  {
    value: "Australia/Sydney",
    city: "Sydney",
    country: "Australia",
    continent: "Oceania",
    flag: "au",
    offset: 600,
  },
  {
    value: "Pacific/Auckland",
    city: "Auckland",
    country: "New Zealand",
    continent: "Oceania",
    flag: "nz",
    offset: 720,
  },
  {
    value: "Pacific/Fiji",
    city: "Suva",
    country: "Fiji",
    continent: "Oceania",
    flag: "fj",
    offset: 720,
  },
  {
    value: "Pacific/Guam",
    city: "Hagåtña",
    country: "Guam",
    continent: "Oceania",
    flag: "gu",
    offset: 600,
  },
  {
    value: "Pacific/Honolulu",
    city: "Honolulu",
    country: "USA (Hawaii)",
    continent: "Oceania",
    flag: "us",
    offset: -600,
  },
  {
    value: "Pacific/Port_Moresby",
    city: "Port Moresby",
    country: "Papua New Guinea",
    continent: "Oceania",
    flag: "pg",
    offset: 600,
  },
  {
    value: "Pacific/Tongatapu",
    city: "Nuku'alofa",
    country: "Tonga",
    continent: "Oceania",
    flag: "to",
    offset: 780,
  },
];

// Helper function to format offset as readable string
export function formatOffset(minutes: number): string {
  const sign = minutes >= 0 ? "+" : "-";
  const absMinutes = Math.abs(minutes);
  const hours = Math.floor(absMinutes / 60);
  const mins = absMinutes % 60;
  if (mins === 0) {
    return `UTC${sign}${hours}`;
  }
  return `UTC${sign}${hours}:${mins.toString().padStart(2, "0")}`;
}

// Helper function to get current time in a timezone
export function getCurrentTimeInTimezone(offsetMinutes: number): string {
  const now = new Date();
  const utc = now.getTime() + now.getTimezoneOffset() * 60000;
  const targetTime = new Date(utc + offsetMinutes * 60000);
  return targetTime.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
}

// Group timezones by continent and sort alphabetically
export function getGroupedTimezones() {
  interface GroupedItem {
    value: string;
    label: string;
    flag: string;
    offset: number;
  }

  const grouped: { [continent: string]: GroupedItem[] } = {};

  TIMEZONES_DATA.forEach((tz) => {
    if (!grouped[tz.continent]) {
      grouped[tz.continent] = [];
    }
    grouped[tz.continent].push({
      value: tz.value,
      label: `${tz.city}, ${tz.country}`,
      flag: tz.flag,
      offset: tz.offset,
    });
  });

  // Sort each continent's timezones alphabetically by label
  Object.keys(grouped).forEach((continent) => {
    grouped[continent].sort((a, b) => a.label.localeCompare(b.label));
  });

  // Convert to Mantine Select group format
  const continentOrder = [
    "UTC",
    "Africa",
    "Americas",
    "Asia",
    "Europe",
    "Oceania",
  ];
  return continentOrder
    .filter((continent) => grouped[continent])
    .map((continent) => ({
      group: continent,
      items: grouped[continent],
    }));
}
