export {
  addContactsToTagResponseSchema,
  contactTagBodySchema,
  contactTagListResponseSchema,
  contactTagsResponseSchema,
  createTagInputSchema,
  createTagSchema,
  deleteTagsRequestSchema,
  peopleTagSchema,
  removeContactsFromTagResponseSchema,
  tagContactsListResponseSchema,
  tagMembershipRequestSchema,
  tagMembersListResponseSchema,
  tagResponseSchema,
  tagSchema,
  tagsListResponseSchema,
  tagUpdateResponseSchema,
  tagWithCountSchema,
  updateTagSchema,
} from "./schema.js";
export type {
  AddContactsToTagResponse,
  ContactTagBody,
  ContactTagListResponse,
  ContactTagsResponse,
  CreateTagInput,
  DeleteTagsRequest,
  PeopleTag,
  RemoveContactsFromTagResponse,
  Tag,
  TagContactsListResponse,
  TagMembershipRequest,
  TagMembersListResponse,
  TagResponse,
  TagsListResponse,
  TagUpdateResponse,
  TagWithCount,
  UpdateTagInput,
} from "./types.js";
