// Generated by scripts/generate-doc-links.mjs — do not edit.
export const DOC_LINKS = {
  "api.authentication": { path: "api/authentication" },
  "bondery.chrome-extension": { path: "bondery/chrome-extension" },
  "bondery.chrome-extension.enriching-contact": { path: "bondery/chrome-extension", hash: "enriching-contact" },
  "concepts.chat": { path: "concepts/chat" },
  "concepts.groups": { path: "concepts/groups" },
  "concepts.interactions": { path: "concepts/interactions" },
  "concepts.map": { path: "concepts/map" },
  "concepts.merge": { path: "concepts/merge" },
  "concepts.myself": { path: "concepts/myself" },
  "concepts.people": { path: "concepts/people" },
  "concepts.reminders": { path: "concepts/reminders" },
} as const;

export type DocId = keyof typeof DOC_LINKS;
