/**
 * Unified local env CLI.
 *
 * Day-to-day:
 *   npm run env
 *     → best-effort Supabase pull → sync apps → check root
 *
 * First clone:
 *   npm run setup:dev
 *
 * Codegen / CI (not day-to-day DX):
 *   npm run env -- --write-examples --write-turbo
 *   npm run env -- --check          # regenerate + fail if git dirty
 */

import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createCliLogger } from "@bondery/helpers/cli";
import {
  applyTransform,
  ENV_MANIFEST,
  getAllRuntimeNames,
  getRuntimeNamesForTarget,
  parseEnvFile,
  resolveCanonicalValue,
  SYNC_TARGETS,
  TURBO_SYSTEM_PASSTHROUGH,
} from "@bondery/helpers/env";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const log = createCliLogger("env");

const GENERATED_HEADER =
  "# Generated by npm run env — do not edit by hand. Edit root .env.local instead.\n";

const ROOT_ENV = join(repoRoot, ".env.local");
const SUPABASE_DIR = join(repoRoot, "apps/supabase-db");

function parseArgs(argv) {
  return {
    check: argv.includes("--check"),
    dryRun: argv.includes("--dry-run"),
    noPull: argv.includes("--no-pull"),
    only: (() => {
      const onlyArg = argv.find((a) => a.startsWith("--only="));
      if (!onlyArg) {
        return null;
      }
      return onlyArg
        .slice("--only=".length)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
    })(),
    skipCheck: argv.includes("--skip-check"),
    writeExamples: argv.includes("--write-examples"),
    writeTurbo: argv.includes("--write-turbo"),
  };
}

function quoteEnvValue(value) {
  if (/[\s#"'$\\]/.test(value) || value === "") {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

function formatEnvFile(vars) {
  const lines = [GENERATED_HEADER];
  let lastGroup = "";
  for (const row of vars) {
    if (row.group !== lastGroup) {
      lines.push("");
      lines.push(`# --- ${row.group} ---`);
      lastGroup = row.group;
    }
    if (row.description) {
      lines.push(`# ${row.description}`);
    }
    lines.push(`${row.key}=${quoteEnvValue(row.value)}`);
  }
  lines.push("");
  return lines.join("\n");
}

function collectTargetVars(targetId, rootEnv, useExamples) {
  const byKey = new Map();

  for (const entry of ENV_MANIFEST) {
    for (const target of entry.targets) {
      if (target.id !== targetId) {
        continue;
      }
      const key = target.runtimeName ?? entry.canonical;
      let value: string | undefined;
      if (useExamples) {
        if (target.deriveFrom) {
          const sourceEntry = ENV_MANIFEST.find((e) => e.canonical === target.deriveFrom);
          const sourceVal = sourceEntry?.exampleValue ?? "";
          value = applyTransform(target.transform, sourceVal);
        } else {
          value = entry.exampleValue;
        }
      } else {
        value = resolveCanonicalValue(rootEnv, entry, target);
      }
      if (value === undefined) {
        continue;
      }
      byKey.set(key, {
        description: entry.description,
        group: entry.group,
        key,
        value,
      });
    }
  }

  return [...byKey.values()].toSorted((a, b) => {
    if (a.group !== b.group) {
      return a.group.localeCompare(b.group);
    }
    return a.key.localeCompare(b.key);
  });
}

function mergeEnvFile(path, newVars, dryRun) {
  const existing = existsSync(path) ? parseEnvFile(path) : {};
  const knownKeys = new Set(Object.keys(newVars));
  const unknown = Object.entries(existing).filter(([k]) => !knownKeys.has(k));

  const rows = Object.entries(newVars).map(([key, value]) => {
    const entry = ENV_MANIFEST.find(
      (e) => e.canonical === key || e.targets.some((t) => (t.runtimeName ?? e.canonical) === key),
    );
    return {
      description: entry?.description ?? "",
      group: entry?.group ?? "Other",
      key,
      value,
    };
  });

  let body = formatEnvFile(
    rows.toSorted((a, b) => {
      if (a.group !== b.group) {
        return a.group.localeCompare(b.group);
      }
      return a.key.localeCompare(b.key);
    }),
  );

  if (unknown.length > 0) {
    body += "\n# --- Preserved (not in manifest) ---\n";
    for (const [key, value] of unknown.toSorted(([a], [b]) => a.localeCompare(b))) {
      body += `${key}=${quoteEnvValue(value)}\n`;
    }
  }

  if (dryRun) {
    log.info(`Would write ${Object.keys(newVars).length} keys → ${path}`);
    return Object.keys(newVars).length;
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body, "utf-8");
  return Object.keys(newVars).length;
}

function writeExamples(dryRun) {
  const rootRows = ENV_MANIFEST.map((e) => ({
    description: e.description,
    group: e.group,
    key: e.canonical,
    value: e.exampleValue,
  }));
  const rootPath = join(repoRoot, ".env.local.example");
  if (!dryRun) {
    writeFileSync(rootPath, formatEnvFile(rootRows), "utf-8");
  }
  log.info(`${dryRun ? "Would write" : "Wrote"} ${rootPath}`);

  for (const target of SYNC_TARGETS) {
    const rows = collectTargetVars(target.id, {}, true);
    const examplePath = join(repoRoot, target.exampleFile);
    if (!dryRun) {
      writeFileSync(examplePath, formatEnvFile(rows), "utf-8");
    }
    log.info(`${dryRun ? "Would write" : "Wrote"} ${examplePath}`);

    if (target.productionExampleFile) {
      const prodRows = rows.map((r) => {
        let value = r.value;
        if (r.key.includes("WEBAPP_URL") && value.includes("localhost")) {
          value = "https://app.usebondery.com";
        } else if (r.key.includes("WEBSITE_URL") && value.includes("localhost")) {
          value = "https://usebondery.com";
        } else if (r.key.includes("API_URL") && value.includes("localhost")) {
          value = "https://api.usebondery.com";
        } else if (r.key === "BONDERY_PUBLIC_POLAR_ENVIRONMENT") {
          value = "production";
        } else if (r.key === "BONDERY_PUBLIC_SUPABASE_URL" && value.includes("127.0.0.1")) {
          value = "https://<your-project-id>.supabase.co";
        }
        return { ...r, value };
      });
      const prodPath = join(repoRoot, target.productionExampleFile);
      if (!dryRun) {
        writeFileSync(prodPath, formatEnvFile(prodRows), "utf-8");
      }
      log.info(`${dryRun ? "Would write" : "Wrote"} ${prodPath}`);
    }
  }
}

function writeTurbo(dryRun) {
  const turboPath = join(repoRoot, "turbo.json");
  const turbo = JSON.parse(readFileSync(turboPath, "utf-8"));

  const globalPassThroughEnv = [...TURBO_SYSTEM_PASSTHROUGH, ...getAllRuntimeNames()];
  turbo.globalPassThroughEnv = [...new Set(globalPassThroughEnv)].toSorted();

  const packageEnv = {
    api: getRuntimeNamesForTarget("api"),
    "chrome-extension": [
      ...getRuntimeNamesForTarget("chrome-extension"),
      "BONDERY_OPS_CHROME_EXTENSION_ID",
      "BONDERY_OPS_CHROME_PUBLISHER_ID",
      "PRIVATE_CHROME_SERVICE_ACCOUNT_KEY_JSON",
      "PRIVATE_CHROME_PRIVATE_SIGNING_KEY",
      "GITHUB_ACTIONS",
      "CI",
    ],
    mobile: [...getRuntimeNamesForTarget("mobile"), "METRO_MAX_WORKERS"],
    webapp: getRuntimeNamesForTarget("webapp"),
    website: getRuntimeNamesForTarget("website"),
  };

  turbo.tasks ??= {};

  const baseBuild = turbo.tasks.build ?? {};
  const buildInherit = {
    dependsOn: baseBuild.dependsOn ?? ["^build"],
    inputs: baseBuild.inputs,
    outputs: baseBuild.outputs,
    passThroughEnv: baseBuild.passThroughEnv,
  };
  const baseDev = turbo.tasks.dev ?? {};
  const devInherit = {
    cache: baseDev.cache ?? false,
    dependsOn: baseDev.dependsOn,
    inputs: baseDev.inputs,
    persistent: baseDev.persistent ?? true,
  };

  for (const taskName of ["build", "dev"]) {
    const task = turbo.tasks[taskName];
    if (task && "env" in task) {
      delete task.env;
    }
  }

  for (const [pkg, env] of Object.entries(packageEnv)) {
    for (const taskName of ["build", "dev"]) {
      const key = `${pkg}#${taskName}`;
      const existing = turbo.tasks[key] ?? {};
      const inherit = taskName === "build" ? buildInherit : devInherit;
      turbo.tasks[key] = {
        ...inherit,
        ...existing,
        dependsOn: existing.dependsOn ?? inherit.dependsOn,
        env: [...new Set(env)].toSorted(),
      };
    }
  }

  const out = `${JSON.stringify(turbo, null, 2)}\n`;
  if (dryRun) {
    log.info("Would update turbo.json env sections");
    return;
  }
  writeFileSync(turboPath, out, "utf-8");
  log.success("Updated turbo.json env sections from manifest");
}

function upsertEnvFile(path, updates) {
  if (!existsSync(path)) {
    const lines = Object.entries(updates).map(([k, v]) => `${k}=${quoteEnvValue(v)}`);
    writeFileSync(path, `${lines.join("\n")}\n`, "utf-8");
    return;
  }

  let content = readFileSync(path, "utf-8");
  for (const [key, value] of Object.entries(updates)) {
    const line = `${key}=${quoteEnvValue(value)}`;
    const re = new RegExp(`^${key}=.*$`, "m");
    if (re.test(content)) {
      content = content.replace(re, line);
    } else {
      content = `${content.trimEnd()}\n${line}\n`;
    }
  }
  writeFileSync(path, content.endsWith("\n") ? content : `${content}\n`, "utf-8");
}

/** @returns {boolean} true if keys were updated */
function pullLocalSupabase(bestEffort) {
  if (!existsSync(ROOT_ENV)) {
    if (bestEffort) {
      log.warn("No .env.local yet — skip Supabase pull");
      return false;
    }
    log.error("Missing .env.local — run: npm run setup:dev");
    process.exit(1);
  }

  let status: Record<string, string> | undefined;
  try {
    const raw = execSync("npx supabase status --output json", {
      cwd: SUPABASE_DIR,
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    status = JSON.parse(raw) as Record<string, string>;
  } catch (error) {
    if (bestEffort) {
      log.warn("Supabase not running — skip pull (start apps/supabase-db, then npm run env)");
      return false;
    }
    log.error(
      "Failed to run supabase status. Start the local stack: cd apps/supabase-db && npm run dev",
    );
    if (error.stderr) {
      log.error(String(error.stderr).trim());
    }
    process.exit(1);
  }

  const apiUrl = status.API_URL ?? status.apiUrl;
  const publishable =
    status.PUBLISHABLE_KEY ?? status.ANON_KEY ?? status.publishableKey ?? status.anonKey;
  const secret = status.SECRET_KEY ?? status.SERVICE_ROLE_KEY ?? status.secretKey;

  if (!apiUrl || !publishable || !secret) {
    if (bestEffort) {
      log.warn("supabase status missing keys — skip pull");
      return false;
    }
    log.error("supabase status JSON missing API_URL / PUBLISHABLE_KEY / SECRET_KEY");
    process.exit(1);
  }

  // Always refresh keys. Preserve a public tunnel URL (e.g. ngrok) when already set —
  // `supabase status` only reports loopback and would clobber OAuth-ready tunnels.
  const rootEnv = parseEnvFile(ROOT_ENV);
  const existingUrl = rootEnv.BONDERY_PUBLIC_SUPABASE_URL ?? "";
  const isTunnelUrl =
    existingUrl.startsWith("https://") && !/localhost|127\.0\.0\.1/.test(existingUrl);

  const updates = {
    BONDERY_PRIVATE_SUPABASE_SECRET_KEY: secret,
    BONDERY_PUBLIC_SUPABASE_PUBLISHABLE_KEY: publishable,
  };
  if (!isTunnelUrl) {
    updates.BONDERY_PUBLIC_SUPABASE_URL = apiUrl;
  }

  upsertEnvFile(ROOT_ENV, updates);
  if (isTunnelUrl) {
    log.success(`Pulled local Supabase keys (kept tunnel URL: ${existingUrl})`);
  } else {
    log.success("Pulled local Supabase URL and keys into .env.local");
  }
  return true;
}

function syncApps(flags) {
  if (!existsSync(ROOT_ENV)) {
    log.error("Missing .env.local — copy from .env.local.example:");
    log.info("  cp .env.local.example .env.local");
    process.exit(1);
  }

  const rootEnv = parseEnvFile(ROOT_ENV);
  const targets = SYNC_TARGETS.filter((t) => !flags.only || flags.only.includes(t.id));
  const summary = [];

  for (const target of targets) {
    const rows = collectTargetVars(target.id, rootEnv, false);
    const asRecord = Object.fromEntries(rows.map((r) => [r.key, r.value]));
    const path = join(repoRoot, target.devFile);
    const count = mergeEnvFile(path, asRecord, flags.dryRun);
    summary.push({ file: target.devFile, target: target.id, vars: count });
  }

  if (summary.length > 0) {
    log.table(summary);
    log.success(
      flags.dryRun ? `Dry run: ${summary.length} targets` : `Synced ${summary.length} targets`,
    );
  }
}

function checkRoot() {
  const environment = process.env.NODE_ENV === "production" ? "production" : "development";
  if (!existsSync(ROOT_ENV)) {
    log.error("Missing .env.local — run: npm run setup:dev");
    process.exit(1);
  }

  const rootEnv = parseEnvFile(ROOT_ENV);
  const missingRoot = [];

  for (const entry of ENV_MANIFEST) {
    if (!entry.requiredIn.includes(environment)) {
      continue;
    }
    const needsRoot = entry.targets.some((t) => !t.deriveFrom);
    if (!needsRoot) {
      continue;
    }
    if (!rootEnv[entry.canonical]) {
      missingRoot.push(entry.canonical);
    }
  }

  if (missingRoot.length > 0) {
    log.error(`Missing required variables in .env.local (${environment}):`);
    for (const name of missingRoot) {
      log.error(`  ${name}`);
    }
    process.exit(1);
  }

  log.success(`Root .env.local has all ${environment} required variables`);

  for (const target of SYNC_TARGETS) {
    const path = join(repoRoot, target.devFile);
    if (!existsSync(path)) {
      log.warn(`Missing ${target.devFile} — run npm run env`);
    }
  }
}

function assertGeneratedFresh() {
  const diff = execSync(
    "git diff --name-only -- .env.local.example turbo.json 'apps/**/.env*.example' 'apps/**/.env.example' 'apps/supabase-db/.env.local.example'",
    { cwd: repoRoot, encoding: "utf-8" },
  ).trim();

  if (diff) {
    log.error("Generated env files / turbo.json are stale. Commit the updates:");
    for (const line of diff.split("\n")) {
      log.error(`  ${line}`);
    }
    process.exit(1);
  }

  log.success("Env examples and turbo.json env sections match the manifest");
}

function main() {
  const flags = parseArgs(process.argv.slice(2));
  const argv = process.argv.slice(2);

  if (flags.check) {
    writeExamples(false);
    writeTurbo(false);
    assertGeneratedFresh();
    return;
  }

  const codegenOnly =
    (flags.writeExamples || flags.writeTurbo) &&
    !argv.some((a) => a.startsWith("--only=")) &&
    argv.every(
      (a) =>
        a === "--write-examples" ||
        a === "--write-turbo" ||
        a === "--dry-run" ||
        a === "--no-pull" ||
        a === "--skip-check",
    );

  if (flags.writeExamples) {
    writeExamples(flags.dryRun);
  }
  if (flags.writeTurbo) {
    writeTurbo(flags.dryRun);
  }
  if (codegenOnly) {
    return;
  }

  // Day-to-day path: pull → sync → check
  if (!flags.noPull) {
    pullLocalSupabase(true);
  }
  syncApps(flags);
  if (!flags.skipCheck && !flags.dryRun) {
    checkRoot();
  }
}

main();
