import { StyleSheet } from "react-native";
import { MOBILE_LAYOUT } from "./layout";

/** Shared floating bottom pill chrome (tab bar + action bar). */
export const floatingBarStyles = StyleSheet.create({
  actionBubble: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: MOBILE_LAYOUT.floatingTabBar.tabBubble / 2,
    height: MOBILE_LAYOUT.floatingTabBar.tabBubble,
    justifyContent: "center",
    width: MOBILE_LAYOUT.floatingTabBar.tabBubble,
  },
  actionRail: {
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 999,
    borderWidth: 1,
    elevation: 4,
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  chromeContainer: {
    alignItems: "center",
    flex: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 16,
  },
  container: {
    alignItems: "center",
    bottom: 0,
    left: 0,
    paddingHorizontal: 16,
    position: "absolute",
    right: 0,
  },
  host: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  speedDialChrome: {
    borderWidth: 1,
    elevation: 4,
    maxWidth: 240,
    overflow: "hidden",
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    width: "100%",
  },
  speedDialMenuColumn: {
    overflow: "hidden",
  },
  tabRail: {
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1,
    elevation: 4,
    flexDirection: "row",
    justifyContent: "space-between",
    maxWidth: 240,
    paddingHorizontal: 10,
    paddingVertical: 8,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    width: "100%",
  },
  tabRailRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
});
