import { StyleSheet } from "react-native";
import { MOBILE_LAYOUT } from "./layout";

/** Shared floating bottom pill chrome (tab bar + action bar). */
export const floatingBarStyles = StyleSheet.create({
  host: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  container: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    paddingHorizontal: 16,
  },
  chromeContainer: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  tabRail: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: 240,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  actionRail: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  actionBubble: {
    width: MOBILE_LAYOUT.floatingTabBar.tabBubble,
    height: MOBILE_LAYOUT.floatingTabBar.tabBubble,
    borderRadius: MOBILE_LAYOUT.floatingTabBar.tabBubble / 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  speedDialChrome: {
    width: "100%",
    maxWidth: 240,
    borderWidth: 1,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
    overflow: "hidden",
  },
  speedDialMenuColumn: {
    overflow: "hidden",
  },
  tabRailRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
});
