import type { CountryCode } from "#phone/types.js";

export const countryCodes: CountryCode[] = [
  {
    code: "US",
    dialCode: "+1",
    flag: "us",
    name: "United States",
    reactMaskExpression: "(000) 000-0000",
  },
  {
    code: "CA",
    dialCode: "+1",
    flag: "ca",
    name: "Canada",
    reactMaskExpression: "000 000 0000",
  },
  { code: "AG", dialCode: "+1-268", flag: "ag", name: "Antigua and Barbuda" },
  { code: "AI", dialCode: "+1-264", flag: "ai", name: "Anguilla" },
  { code: "AS", dialCode: "+1-684", flag: "as", name: "American Samoa" },
  { code: "BB", dialCode: "+1-246", flag: "bb", name: "Barbados" },
  { code: "BM", dialCode: "+1-441", flag: "bm", name: "Bermuda" },
  { code: "BS", dialCode: "+1-242", flag: "bs", name: "Bahamas" },
  { code: "DM", dialCode: "+1-767", flag: "dm", name: "Dominica" },
  { code: "DO", dialCode: "+1-809", flag: "do", name: "Dominican Republic" },
  { code: "DO", dialCode: "+1-829", flag: "do", name: "Dominican Republic" },
  { code: "DO", dialCode: "+1-849", flag: "do", name: "Dominican Republic" },
  { code: "GD", dialCode: "+1-473", flag: "gd", name: "Grenada" },
  { code: "GU", dialCode: "+1-671", flag: "gu", name: "Guam" },
  { code: "JM", dialCode: "+1-876", flag: "jm", name: "Jamaica" },
  { code: "KN", dialCode: "+1-869", flag: "kn", name: "Saint Kitts and Nevis" },
  { code: "KY", dialCode: "+1-345", flag: "ky", name: "Cayman Islands" },
  { code: "LC", dialCode: "+1-758", flag: "lc", name: "Saint Lucia" },
  {
    code: "MP",
    dialCode: "+1-670",
    flag: "mp",
    name: "Northern Mariana Islands",
  },
  { code: "MS", dialCode: "+1-664", flag: "ms", name: "Montserrat" },
  { code: "PR", dialCode: "+1-787", flag: "pr", name: "Puerto Rico" },
  { code: "PR", dialCode: "+1-939", flag: "pr", name: "Puerto Rico" },
  { code: "SX", dialCode: "+1-721", flag: "sx", name: "Sint Maarten" },
  {
    code: "TC",
    dialCode: "+1-649",
    flag: "tc",
    name: "Turks and Caicos Islands",
  },
  { code: "TT", dialCode: "+1-868", flag: "tt", name: "Trinidad and Tobago" },
  {
    code: "VC",
    dialCode: "+1-784",
    flag: "vc",
    name: "Saint Vincent and the Grenadines",
  },
  {
    code: "VG",
    dialCode: "+1-284",
    flag: "vg",
    name: "British Virgin Islands",
  },
  { code: "VI", dialCode: "+1-340", flag: "vi", name: "U.S. Virgin Islands" },
  {
    code: "GB",
    dialCode: "+44",
    flag: "gb",
    name: "United Kingdom",
    reactMaskExpression: "0000 000 000",
  },
  {
    code: "DE",
    dialCode: "+49",
    flag: "de",
    name: "Germany",
    reactMaskExpression: "0000 0000000",
  },
  {
    code: "FR",
    dialCode: "+33",
    flag: "fr",
    name: "France",
    reactMaskExpression: "00 00 00 00 00",
  },
  {
    code: "IT",
    dialCode: "+39",
    flag: "it",
    name: "Italy",
    reactMaskExpression: "000 000 0000",
  },
  {
    code: "ES",
    dialCode: "+34",
    flag: "es",
    name: "Spain",
    reactMaskExpression: "000 000 000",
  },
  { code: "RU", dialCode: "+7", flag: "ru", name: "Russia" },
  { code: "KZ", dialCode: "+7", flag: "kz", name: "Kazakhstan" },
  { code: "EG", dialCode: "+20", flag: "eg", name: "Egypt" },
  { code: "ZA", dialCode: "+27", flag: "za", name: "South Africa" },
  { code: "GR", dialCode: "+30", flag: "gr", name: "Greece" },
  {
    code: "NL",
    dialCode: "+31",
    flag: "nl",
    name: "Netherlands",
    reactMaskExpression: "00 00000000",
  },
  {
    code: "BE",
    dialCode: "+32",
    flag: "be",
    name: "Belgium",
    reactMaskExpression: "000 00 00 00",
  },
  {
    code: "PT",
    dialCode: "+351",
    flag: "pt",
    name: "Portugal",
    reactMaskExpression: "000 000 000",
  },
  {
    code: "IE",
    dialCode: "+353",
    flag: "ie",
    name: "Ireland",
    reactMaskExpression: "00 000 0000",
  },
  { code: "LU", dialCode: "+352", flag: "lu", name: "Luxembourg" },
  { code: "IS", dialCode: "+354", flag: "is", name: "Iceland" },
  { code: "AL", dialCode: "+355", flag: "al", name: "Albania" },
  { code: "MT", dialCode: "+356", flag: "mt", name: "Malta" },
  { code: "CY", dialCode: "+357", flag: "cy", name: "Cyprus" },
  {
    code: "FI",
    dialCode: "+358",
    flag: "fi",
    name: "Finland",
    reactMaskExpression: "00 000 0000",
  },
  { code: "BG", dialCode: "+359", flag: "bg", name: "Bulgaria" },
  { code: "HU", dialCode: "+36", flag: "hu", name: "Hungary" },
  { code: "LT", dialCode: "+370", flag: "lt", name: "Lithuania" },
  { code: "LV", dialCode: "+371", flag: "lv", name: "Latvia" },
  { code: "EE", dialCode: "+372", flag: "ee", name: "Estonia" },
  { code: "MD", dialCode: "+373", flag: "md", name: "Moldova" },
  { code: "AM", dialCode: "+374", flag: "am", name: "Armenia" },
  { code: "BY", dialCode: "+375", flag: "by", name: "Belarus" },
  { code: "AD", dialCode: "+376", flag: "ad", name: "Andorra" },
  { code: "MC", dialCode: "+377", flag: "mc", name: "Monaco" },
  { code: "SM", dialCode: "+378", flag: "sm", name: "San Marino" },
  { code: "VA", dialCode: "+379", flag: "va", name: "Vatican City" },
  { code: "UA", dialCode: "+380", flag: "ua", name: "Ukraine" },
  { code: "RS", dialCode: "+381", flag: "rs", name: "Serbia" },
  { code: "ME", dialCode: "+382", flag: "me", name: "Montenegro" },
  { code: "HR", dialCode: "+385", flag: "hr", name: "Croatia" },
  { code: "SI", dialCode: "+386", flag: "si", name: "Slovenia" },
  { code: "BA", dialCode: "+387", flag: "ba", name: "Bosnia and Herzegovina" },
  { code: "MK", dialCode: "+389", flag: "mk", name: "North Macedonia" },
  {
    code: "CZ",
    dialCode: "+420",
    flag: "cz",
    name: "Czech Republic",
    reactMaskExpression: "000 000 000",
  },
  {
    code: "SK",
    dialCode: "+421",
    flag: "sk",
    name: "Slovakia",
    reactMaskExpression: "000 000 000",
  },
  { code: "LI", dialCode: "+423", flag: "li", name: "Liechtenstein" },
  {
    code: "AT",
    dialCode: "+43",
    flag: "at",
    name: "Austria",
    reactMaskExpression: "0000 000000",
  },
  { code: "GB", dialCode: "+44", flag: "gb", name: "United Kingdom" },
  {
    code: "DK",
    dialCode: "+45",
    flag: "dk",
    name: "Denmark",
    reactMaskExpression: "00 00 00 00",
  },
  {
    code: "SE",
    dialCode: "+46",
    flag: "se",
    name: "Sweden",
    reactMaskExpression: "00 000 00 00",
  },
  {
    code: "NO",
    dialCode: "+47",
    flag: "no",
    name: "Norway",
    reactMaskExpression: "000 00 000",
  },
  {
    code: "PL",
    dialCode: "+48",
    flag: "pl",
    name: "Poland",
    reactMaskExpression: "000 000 000",
  },
  { code: "DE", dialCode: "+49", flag: "de", name: "Germany" },
  { code: "PE", dialCode: "+51", flag: "pe", name: "Peru" },
  {
    code: "MX",
    dialCode: "+52",
    flag: "mx",
    name: "Mexico",
    reactMaskExpression: "000 000 0000",
  },
  { code: "CU", dialCode: "+53", flag: "cu", name: "Cuba" },
  {
    code: "AR",
    dialCode: "+54",
    flag: "ar",
    name: "Argentina",
    reactMaskExpression: "00 0000 0000",
  },
  {
    code: "BR",
    dialCode: "+55",
    flag: "br",
    name: "Brazil",
    reactMaskExpression: "00 00000 0000",
  },
  { code: "CL", dialCode: "+56", flag: "cl", name: "Chile" },
  { code: "CO", dialCode: "+57", flag: "co", name: "Colombia" },
  { code: "VE", dialCode: "+58", flag: "ve", name: "Venezuela" },
  { code: "MY", dialCode: "+60", flag: "my", name: "Malaysia" },
  {
    code: "AU",
    dialCode: "+61",
    flag: "au",
    name: "Australia",
    reactMaskExpression: "0000 000 000",
  },
  { code: "ID", dialCode: "+62", flag: "id", name: "Indonesia" },
  { code: "PH", dialCode: "+63", flag: "ph", name: "Philippines" },
  {
    code: "NZ",
    dialCode: "+64",
    flag: "nz",
    name: "New Zealand",
    reactMaskExpression: "000 000 0000",
  },
  { code: "SG", dialCode: "+65", flag: "sg", name: "Singapore" },
  { code: "TH", dialCode: "+66", flag: "th", name: "Thailand" },
  {
    code: "JP",
    dialCode: "+81",
    flag: "jp",
    name: "Japan",
    reactMaskExpression: "00 0000 0000",
  },
  {
    code: "KR",
    dialCode: "+82",
    flag: "kr",
    name: "South Korea",
    reactMaskExpression: "00 0000 0000",
  },
  { code: "VN", dialCode: "+84", flag: "vn", name: "Vietnam" },
  {
    code: "CN",
    dialCode: "+86",
    flag: "cn",
    name: "China",
    reactMaskExpression: "000 0000 0000",
  },
  { code: "TR", dialCode: "+90", flag: "tr", name: "Turkey" },
  {
    code: "IN",
    dialCode: "+91",
    flag: "in",
    name: "India",
    reactMaskExpression: "00000 00000",
  },
  { code: "PK", dialCode: "+92", flag: "pk", name: "Pakistan" },
  { code: "AF", dialCode: "+93", flag: "af", name: "Afghanistan" },
  { code: "LK", dialCode: "+94", flag: "lk", name: "Sri Lanka" },
  { code: "MM", dialCode: "+95", flag: "mm", name: "Myanmar" },
  { code: "IR", dialCode: "+98", flag: "ir", name: "Iran" },
  { code: "SS", dialCode: "+211", flag: "ss", name: "South Sudan" },
  { code: "MA", dialCode: "+212", flag: "ma", name: "Morocco" },
  { code: "DZ", dialCode: "+213", flag: "dz", name: "Algeria" },
  { code: "TN", dialCode: "+216", flag: "tn", name: "Tunisia" },
  { code: "LY", dialCode: "+218", flag: "ly", name: "Libya" },
  { code: "GM", dialCode: "+220", flag: "gm", name: "Gambia" },
  { code: "SN", dialCode: "+221", flag: "sn", name: "Senegal" },
  { code: "MR", dialCode: "+222", flag: "mr", name: "Mauritania" },
  { code: "ML", dialCode: "+223", flag: "ml", name: "Mali" },
  { code: "GN", dialCode: "+224", flag: "gn", name: "Guinea" },
  { code: "CI", dialCode: "+225", flag: "ci", name: "Ivory Coast" },
  { code: "BF", dialCode: "+226", flag: "bf", name: "Burkina Faso" },
  { code: "NE", dialCode: "+227", flag: "ne", name: "Niger" },
  { code: "TG", dialCode: "+228", flag: "tg", name: "Togo" },
  { code: "BJ", dialCode: "+229", flag: "bj", name: "Benin" },
  { code: "MU", dialCode: "+230", flag: "mu", name: "Mauritius" },
  { code: "LR", dialCode: "+231", flag: "lr", name: "Liberia" },
  { code: "SL", dialCode: "+232", flag: "sl", name: "Sierra Leone" },
  { code: "GH", dialCode: "+233", flag: "gh", name: "Ghana" },
  { code: "NG", dialCode: "+234", flag: "ng", name: "Nigeria" },
  { code: "TD", dialCode: "+235", flag: "td", name: "Chad" },
  {
    code: "CF",
    dialCode: "+236",
    flag: "cf",
    name: "Central African Republic",
  },
  { code: "CM", dialCode: "+237", flag: "cm", name: "Cameroon" },
  { code: "CV", dialCode: "+238", flag: "cv", name: "Cape Verde" },
  { code: "ST", dialCode: "+239", flag: "st", name: "Sao Tome and Principe" },
  { code: "GQ", dialCode: "+240", flag: "gq", name: "Equatorial Guinea" },
  { code: "GA", dialCode: "+241", flag: "ga", name: "Gabon" },
  { code: "CG", dialCode: "+242", flag: "cg", name: "Republic of the Congo" },
  {
    code: "CD",
    dialCode: "+243",
    flag: "cd",
    name: "Democratic Republic of the Congo",
  },
  { code: "AO", dialCode: "+244", flag: "ao", name: "Angola" },
  { code: "GW", dialCode: "+245", flag: "gw", name: "Guinea-Bissau" },
  {
    code: "IO",
    dialCode: "+246",
    flag: "io",
    name: "British Indian Ocean Territory",
  },
  { code: "SC", dialCode: "+248", flag: "sc", name: "Seychelles" },
  { code: "SD", dialCode: "+249", flag: "sd", name: "Sudan" },
  { code: "RW", dialCode: "+250", flag: "rw", name: "Rwanda" },
  { code: "ET", dialCode: "+251", flag: "et", name: "Ethiopia" },
  { code: "SO", dialCode: "+252", flag: "so", name: "Somalia" },
  { code: "DJ", dialCode: "+253", flag: "dj", name: "Djibouti" },
  { code: "KE", dialCode: "+254", flag: "ke", name: "Kenya" },
  { code: "TZ", dialCode: "+255", flag: "tz", name: "Tanzania" },
  { code: "UG", dialCode: "+256", flag: "ug", name: "Uganda" },
  { code: "BI", dialCode: "+257", flag: "bi", name: "Burundi" },
  { code: "MZ", dialCode: "+258", flag: "mz", name: "Mozambique" },
  { code: "ZM", dialCode: "+260", flag: "zm", name: "Zambia" },
  { code: "MG", dialCode: "+261", flag: "mg", name: "Madagascar" },
  { code: "RE", dialCode: "+262", flag: "re", name: "Réunion" },
  { code: "ZW", dialCode: "+263", flag: "zw", name: "Zimbabwe" },
  { code: "NA", dialCode: "+264", flag: "na", name: "Namibia" },
  { code: "MW", dialCode: "+265", flag: "mw", name: "Malawi" },
  { code: "LS", dialCode: "+266", flag: "ls", name: "Lesotho" },
  { code: "BW", dialCode: "+267", flag: "bw", name: "Botswana" },
  { code: "SZ", dialCode: "+268", flag: "sz", name: "Eswatini" },
  { code: "KM", dialCode: "+269", flag: "km", name: "Comoros" },
  { code: "SH", dialCode: "+290", flag: "sh", name: "Saint Helena" },
  { code: "ER", dialCode: "+291", flag: "er", name: "Eritrea" },
  { code: "AW", dialCode: "+297", flag: "aw", name: "Aruba" },
  { code: "FO", dialCode: "+298", flag: "fo", name: "Faroe Islands" },
  { code: "GL", dialCode: "+299", flag: "gl", name: "Greenland" },
  { code: "GI", dialCode: "+350", flag: "gi", name: "Gibraltar" },
  { code: "PT", dialCode: "+351", flag: "pt", name: "Portugal" },
  { code: "LU", dialCode: "+352", flag: "lu", name: "Luxembourg" },
  { code: "IE", dialCode: "+353", flag: "ie", name: "Ireland" },
  { code: "IS", dialCode: "+354", flag: "is", name: "Iceland" },
  { code: "AL", dialCode: "+355", flag: "al", name: "Albania" },
  { code: "MT", dialCode: "+356", flag: "mt", name: "Malta" },
  { code: "CY", dialCode: "+357", flag: "cy", name: "Cyprus" },
  { code: "FI", dialCode: "+358", flag: "fi", name: "Finland" },
  { code: "BG", dialCode: "+359", flag: "bg", name: "Bulgaria" },
  { code: "LT", dialCode: "+370", flag: "lt", name: "Lithuania" },
  { code: "LV", dialCode: "+371", flag: "lv", name: "Latvia" },
  { code: "EE", dialCode: "+372", flag: "ee", name: "Estonia" },
  { code: "MD", dialCode: "+373", flag: "md", name: "Moldova" },
  { code: "AM", dialCode: "+374", flag: "am", name: "Armenia" },
  { code: "BY", dialCode: "+375", flag: "by", name: "Belarus" },
  { code: "AD", dialCode: "+376", flag: "ad", name: "Andorra" },
  { code: "MC", dialCode: "+377", flag: "mc", name: "Monaco" },
  { code: "SM", dialCode: "+378", flag: "sm", name: "San Marino" },
  { code: "VA", dialCode: "+379", flag: "va", name: "Vatican City" },
  { code: "UA", dialCode: "+380", flag: "ua", name: "Ukraine" },
  { code: "RS", dialCode: "+381", flag: "rs", name: "Serbia" },
  { code: "ME", dialCode: "+382", flag: "me", name: "Montenegro" },
  { code: "HR", dialCode: "+385", flag: "hr", name: "Croatia" },
  { code: "SI", dialCode: "+386", flag: "si", name: "Slovenia" },
  { code: "BA", dialCode: "+387", flag: "ba", name: "Bosnia and Herzegovina" },
  { code: "MK", dialCode: "+389", flag: "mk", name: "North Macedonia" },
  { code: "CZ", dialCode: "+420", flag: "cz", name: "Czech Republic" },
  { code: "SK", dialCode: "+421", flag: "sk", name: "Slovakia" },
  { code: "LI", dialCode: "+423", flag: "li", name: "Liechtenstein" },
  { code: "AT", dialCode: "+43", flag: "at", name: "Austria" },
  { code: "GB", dialCode: "+44", flag: "gb", name: "United Kingdom" },
  { code: "DK", dialCode: "+45", flag: "dk", name: "Denmark" },
  { code: "SE", dialCode: "+46", flag: "se", name: "Sweden" },
  { code: "NO", dialCode: "+47", flag: "no", name: "Norway" },
  { code: "PL", dialCode: "+48", flag: "pl", name: "Poland" },
  { code: "DE", dialCode: "+49", flag: "de", name: "Germany" },
  { code: "PE", dialCode: "+51", flag: "pe", name: "Peru" },
  { code: "MX", dialCode: "+52", flag: "mx", name: "Mexico" },
  { code: "CU", dialCode: "+53", flag: "cu", name: "Cuba" },
  { code: "AR", dialCode: "+54", flag: "ar", name: "Argentina" },
  { code: "BR", dialCode: "+55", flag: "br", name: "Brazil" },
  { code: "CL", dialCode: "+56", flag: "cl", name: "Chile" },
  { code: "CO", dialCode: "+57", flag: "co", name: "Colombia" },
  { code: "VE", dialCode: "+58", flag: "ve", name: "Venezuela" },
  { code: "MY", dialCode: "+60", flag: "my", name: "Malaysia" },
  { code: "AU", dialCode: "+61", flag: "au", name: "Australia" },
  { code: "ID", dialCode: "+62", flag: "id", name: "Indonesia" },
  { code: "PH", dialCode: "+63", flag: "ph", name: "Philippines" },
  { code: "NZ", dialCode: "+64", flag: "nz", name: "New Zealand" },
  { code: "SG", dialCode: "+65", flag: "sg", name: "Singapore" },
  { code: "TH", dialCode: "+66", flag: "th", name: "Thailand" },
  { code: "JP", dialCode: "+81", flag: "jp", name: "Japan" },
  { code: "KR", dialCode: "+82", flag: "kr", name: "South Korea" },
  { code: "VN", dialCode: "+84", flag: "vn", name: "Vietnam" },
  { code: "CN", dialCode: "+86", flag: "cn", name: "China" },
  { code: "TR", dialCode: "+90", flag: "tr", name: "Turkey" },
  { code: "IN", dialCode: "+91", flag: "in", name: "India" },
  { code: "PK", dialCode: "+92", flag: "pk", name: "Pakistan" },
  { code: "AF", dialCode: "+93", flag: "af", name: "Afghanistan" },
  { code: "LK", dialCode: "+94", flag: "lk", name: "Sri Lanka" },
  { code: "MM", dialCode: "+95", flag: "mm", name: "Myanmar" },
  { code: "IR", dialCode: "+98", flag: "ir", name: "Iran" },
  // ... (full ITU-T E.164 list continues)
];

export const SORTED_COUNTRY_CODES_BY_DIAL_LENGTH = [...countryCodes].sort(
  (a, b) => b.dialCode.length - a.dialCode.length,
);
