export {
  declineMergeRecommendationResponseSchema,
  mergeAvatarIdentityResponseSchema,
  mergeConflictChoiceSchema,
  mergeConflictFieldSchema,
  mergeContactsRequestSchema,
  mergeContactsResponseSchema,
  mergeRecommendationReasonSchema,
  mergeRecommendationSchema,
  mergeRecommendationsCountResponseSchema,
  mergeRecommendationsResponseSchema,
  refreshMergeRecommendationsResponseSchema,
} from "./schema.js";
export type {
  DeclineMergeRecommendationResponse,
  MergeAvatarIdentityResponse,
  MergeConflictChoice,
  MergeConflictField,
  MergeContactsRequest,
  MergeContactsResponse,
  MergeRecommendation,
  MergeRecommendationReason,
  MergeRecommendationsCountResponse,
  MergeRecommendationsResponse,
  RefreshMergeRecommendationsResponse,
} from "./types.js";
